"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { Activity, Bot, BookOpenCheck, ChevronLeft, CircleDollarSign, DatabaseZap, Search, ShieldCheck, WalletCards } from "lucide-react";
import type { RadarDashboardData, RadarViewRow } from "@/lib/radar/view";
import { chainLabel, chainTone } from "@/lib/chains";
import { formatShanghaiDateTime, formatTokenPrice, formatUsdCompact } from "@/lib/market-format";

const tabs = [
  ["new", "实时候选"], ["approved", "AI认可"], ["trade_ready", "交易数据就绪"], ["paper_ready", "可进入Paper"], ["x_anomalies", "X抓取异常"], ["observing", "观察中"], ["bought", "已买入"], ["closed", "已止盈/已清仓"], ["rejected", "被拒绝"], ["orders", "模拟交易记录"], ["learning", "叙事学习"], ["strategy", "策略设置"], ["wallet", "钱包与自动交易状态"],
] as const;
type TabKey = typeof tabs[number][0];

function age(created: string | null, now = Date.now()) { if (!created) return "--"; const ms = now - Date.parse(created); if (!Number.isFinite(ms)) return "--"; const min = Math.max(0, Math.floor(ms / 60_000)); return min < 60 ? `${min}分钟` : min < 1440 ? `${Math.floor(min / 60)}小时` : `${Math.floor(min / 1440)}天`; }
function pct(bps: number | null) { return bps === null ? "--" : `${bps >= 0 ? "+" : ""}${(bps / 100).toFixed(2)}%`; }
function sourceState(row: RadarViewRow) { try { const parsed = JSON.parse(row.sourceStatus) as Record<string, string>; return Object.entries(parsed).map(([key, value]) => `${key}: ${value}`).join(" · ") || "--"; } catch { return row.sourceStatus || "--"; } }

function RadarCard({ row }: { row: RadarViewRow }) {
  const narrativeTone = row.narrativeStatus === "COMPLETED" ? "text-emerald-300 border-emerald-300/20 bg-emerald-300/[0.07]" : row.narrativeStatus === "FAILED" ? "text-rose-300 border-rose-300/20 bg-rose-300/[0.07]" : "text-amber-200 border-amber-300/20 bg-amber-300/[0.07]";
  const tradeTone = row.tradeStatus === "PASS" ? "text-emerald-300 border-emerald-300/20 bg-emerald-300/[0.07]" : row.tradeStatus === "FAIL" ? "text-rose-300 border-rose-300/20 bg-rose-300/[0.07]" : "text-amber-200 border-amber-300/20 bg-amber-300/[0.07]";
  return <article className="min-w-0 overflow-hidden rounded-2xl border border-white/[0.08] bg-[#0b1018]/95 p-4 shadow-[0_18px_50px_rgba(0,0,0,.18)]">
    <div className="mb-3 flex items-center gap-2 text-[11px] text-slate-500"><Image unoptimized src={row.avatarUrl} alt="" width={36} height={36} className="h-9 w-9 shrink-0 rounded-xl border border-white/10 bg-black/20 object-cover"/><span>头像 {row.avatarStatus}</span><span>· 补全 {row.enrichmentStatus}</span></div>
    <div className="flex min-w-0 flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex min-w-0 flex-wrap items-center gap-2"><h3 className="truncate text-base font-semibold text-slate-100">{row.symbol}</h3><span className={`rounded-md border px-2 py-0.5 text-[11px] ${chainTone(row.chain)}`}>{chainLabel(row.chain)}</span><span className="rounded-md border border-cyan-300/15 bg-cyan-300/[0.06] px-2 py-0.5 text-[11px] text-cyan-200">土狗雷达</span></div><p className="mt-1 truncate text-xs text-slate-500">{row.name}</p></div><div className="flex flex-wrap justify-end gap-1.5"><span className={`rounded-lg border px-2 py-1 text-[11px] font-medium ${narrativeTone}`}>叙事 {row.narrativeStatus}</span><span className={`rounded-lg border px-2 py-1 text-[11px] font-medium ${tradeTone}`}>交易 {row.tradeStatus}</span></div></div>
    <div className="mt-3 min-w-0 rounded-lg border border-white/[0.06] bg-black/15 px-3 py-2 font-mono text-[11px] text-slate-400"><div className="break-all">Token {row.tokenAddress}</div><div className="mt-1 break-all">Pair {row.pairAddress || "待解析"}{row.dexId ? ` · DEX ${row.dexId}` : ""}</div></div>
    <div className="mt-3 grid grid-cols-2 gap-x-3 gap-y-2 text-xs sm:grid-cols-4"><Metric label="价格" value={formatTokenPrice(row.price === null ? null : Number(row.price))}/><Metric label="市值" value={row.marketCap === null ? "--" : formatUsdCompact(row.marketCap)}/><Metric label="流动性" value={row.liquidity === null ? "--" : formatUsdCompact(row.liquidity)}/><Metric label="24H成交额" value={row.volume24h === null ? "--" : formatUsdCompact(row.volume24h)}/><Metric label="持币人数" value={row.holders?.toLocaleString() || "--"}/><Metric label="买家/卖家" value={row.buyers === null || row.sellers === null ? "--" : `${row.buyers}/${row.sellers}`}/><Metric label="KOL/聪明钱" value={String(row.smartMoneyCount)}/><Metric label="币龄" value={age(row.poolCreatedAt)}/></div>
    <div className="mt-3 grid grid-cols-4 gap-2"><Score label="安全" value={row.securityScore}/><Score label="叙事" value={row.narrativeScore}/><Score label="动量" value={row.momentumScore}/><Score label="综合" value={row.totalScore}/></div>
    {row.sourceProjectDescription ? <div className="mt-3 rounded-lg border border-amber-300/15 bg-amber-300/[0.05] px-3 py-2 text-xs leading-5 text-amber-100/80"><b>初始简介：</b>{row.sourceProjectDescription}<div className="text-amber-100/55">这是来源页面提供的初始简介，尚不代表叙事已被外部证实。</div></div> : null}
    <p className="mt-3 text-sm leading-6 text-slate-300">{row.narrativeSummary}</p>
    <div className="mt-2 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><Metric label="题材潜力" value={row.memePotentialScore === null ? "--" : String(row.memePotentialScore)}/><Metric label="事件证据" value={row.catalystEvidenceScore === null ? "--" : String(row.catalystEvidenceScore)}/><Metric label="新鲜度/情绪" value={`${row.narrativeFreshness ?? "--"}/${row.narrativeSentiment ?? "--"}`}/><Metric label="提前量/阶段" value={`${row.narrativeLead ?? "--"}/${row.narrativeStage}`}/></div>
    {row.xFetchStatus === "EXCESSIVE_X_FETCH" || row.xFetchStatus === "FETCH_WARNING" ? <p className="mt-2 rounded-lg border border-rose-300/20 bg-rose-300/[0.06] px-3 py-2 text-xs text-rose-200">{row.xFetchStatus} · 后台抓取 {row.xPostsFetched ?? "未知"} 条帖子；该候选禁止自动重搜。</p> : null}
    <div className="mt-3 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><Metric label="Pair / 流动性" value={`${row.pairStatus} / ${row.liquidityStatus}`}/><Metric label="24H独立买/卖家" value={row.uniqueBuyers24h === null || row.uniqueSellers24h === null ? "--" : `${row.uniqueBuyers24h}/${row.uniqueSellers24h}`}/><Metric label="24H买/卖交易" value={row.buyTx24h === null || row.sellTx24h === null ? "--" : `${row.buyTx24h}/${row.sellTx24h}`}/><Metric label="传播 / 提前量" value={`${row.propagationStage} / ${row.leadTiming}`}/><Metric label="Token年龄" value={age(row.tokenCreatedAt)}/><Metric label="池龄" value={age(row.poolCreatedAt)}/><Metric label="系统首次发现" value={age(row.systemFirstSeenAt)}/><Metric label="来源事件" value={`${row.sourceEventCount}（重复${row.sourceRepeatCount}）`}/></div>
    {row.enrichmentError ? <p className="mt-2 break-words rounded-lg border border-amber-300/15 bg-amber-300/[0.04] px-3 py-2 text-xs text-amber-100/70">补全原因：{row.enrichmentError}</p> : null}
    <p className={`mt-3 rounded-lg border px-3 py-2 text-xs ${tradeTone}`}>交易数据：{row.tradeDataStage} · {row.tradeShortReason}</p>
    <div className="mt-2 grid gap-1 text-xs text-slate-400">
      <Detail label="查看交易检查"><ul className="space-y-1">{row.tradeChecks.map((item) => <li key={item.key}><b className="mr-1 text-slate-300">{item.state}</b>{item.label}：{item.reason}</li>)}</ul></Detail>
      <Detail label="查看风险评论"><ul className="space-y-1">{row.riskComments.map((item) => <li key={item}>· {item}</li>)}</ul></Detail>
      <Detail label="查看叙事证据"><ul className="space-y-2">{row.narrativeEvidence.length ? row.narrativeEvidence.map((item, index) => <li key={`${item.source_url}-${index}`}><span className="mr-1 rounded border border-white/10 px-1 py-0.5 text-[10px]">{item.evidence_relation}</span>{item.source_url ? <a className="text-cyan-300 hover:underline" href={item.source_url} target="_blank" rel="noopener noreferrer">{item.author_handle ? `@${item.author_handle}` : item.author_name || "X原帖"} · {item.short_summary}</a> : <span>{item.short_summary} · 历史证据链接未保存</span>} · {item.published_at ? formatShanghaiDateTime(item.published_at) : "时间未知"}</li>) : <li>来源链接未返回；未展示搜索动作说明。</li>}</ul></Detail>
      <Detail label="查看原始数据"><pre className="max-h-48 overflow-auto whitespace-pre-wrap break-all font-mono text-[10px]">{row.rawInput}</pre></Detail>
    </div>
    <div className="mt-3 grid grid-cols-2 gap-2 border-t border-white/[0.06] pt-3 text-[11px] text-slate-500 sm:grid-cols-4"><span>来源：{row.signalSource}</span><span>类型：{row.signalType}</span><span>发现：{formatShanghaiDateTime(row.firstSeenAt)}</span><span>数据：{row.dataFreshnessMs === null ? "--" : `${Math.round(row.dataFreshnessMs / 1000)}s`}</span></div>
    <div className="mt-2 truncate text-[11px] text-slate-600">源状态：{sourceState(row)} · X搜索 {row.xSearchCalls ?? "--"} · 后台抓取 {row.xPostsFetched ?? "--"} · 保存证据 {row.narrativeEvidence.length} · 费用 {row.xCostUsd === null ? "--" : `$${row.xCostUsd.toFixed(4)}`}</div>
    <div className="mt-3 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><Metric label="模拟持仓" value={row.paperEntered ? "已进入" : "未进入"}/><Metric label="计划买入" value={row.plannedBuyUsd ? `$${row.plannedBuyUsd}` : "--"}/><Metric label="当前/最高收益" value={`${pct(row.currentReturnBps)} / ${pct(row.maxReturnBps)}`}/><Metric label="止盈/剩余" value={`${row.takeProfitCount} / ${row.remainingPosition || "--"}`}/></div>
  </article>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="min-w-0"><div className="text-[11px] text-slate-600">{label}</div><div className="mt-0.5 truncate text-slate-300">{value}</div></div>; }
function Score({ label, value }: { label: string; value: number | null }) { return <div className="rounded-lg border border-white/[0.06] bg-white/[0.025] px-2 py-2 text-center"><div className="text-[10px] text-slate-600">{label}</div><div className="mt-0.5 text-sm font-semibold text-cyan-200">{value === null ? "--" : value}</div></div>; }
function Detail({ label, children }: { label: string; children: React.ReactNode }) { return <details className="rounded-lg border border-white/[0.06] bg-black/10 px-3 py-2"><summary className="cursor-pointer select-none text-slate-400">{label}</summary><div className="mt-2 leading-5 text-slate-500">{children}</div></details>; }

export default function RadarDashboard({ initial, walletLoginEnabled, autoTradeEnabled, walletConnectEnabled }: { initial: RadarDashboardData; walletLoginEnabled: boolean; autoTradeEnabled: boolean; walletConnectEnabled: boolean }) {
  const router = useRouter();
  const [data, setData] = useState(initial); const [tab, setTab] = useState<TabKey>("new"); const [query, setQuery] = useState(""); const [loadingMore, setLoadingMore] = useState(false);
  useEffect(() => { let active = true; const refresh = async () => { try { const response = await fetch("/api/radar/signals?limit=40", { cache: "no-store" }); if (response.ok && active) { const incoming = await response.json() as RadarDashboardData; setData((current) => { const merged = new Map(current.rows.map((row) => [row.id, row])); for (const row of incoming.rows) merged.set(row.id, row); return { ...incoming, rows: [...merged.values()].sort((a, b) => Date.parse(b.firstSeenAt) - Date.parse(a.firstSeenAt)), nextOffset: current.rows.length > incoming.rows.length ? current.nextOffset : incoming.nextOffset }; }); } } catch { /* retain last-known-good UI */ } }; const timer = window.setInterval(refresh, 15_000); const visible = () => { if (!document.hidden) void refresh(); }; document.addEventListener("visibilitychange", visible); return () => { active = false; window.clearInterval(timer); document.removeEventListener("visibilitychange", visible); }; }, []);
  const rows = useMemo(() => data.rows.filter((row) => `${row.symbol} ${row.name} ${row.tokenAddress}`.toLowerCase().includes(query.toLowerCase())).filter((row) => tab === "new" ? true : tab === "approved" ? row.aiDecision === "APPROVE" : tab === "trade_ready" ? row.tradeStatus === "PASS" : tab === "paper_ready" ? row.aiDecision === "APPROVE" && row.tradeStatus === "PASS" : tab === "x_anomalies" ? ["FETCH_WARNING", "EXCESSIVE_X_FETCH"].includes(row.xFetchStatus) : tab === "observing" ? row.aiDecision === "HOLD" : tab === "rejected" ? row.aiDecision === "REJECT" : tab === "bought" ? row.paperEntered && row.remainingPosition !== "0" : tab === "closed" ? row.paperEntered && row.remainingPosition === "0" : false), [data.rows, query, tab]);
  return <main className="min-h-screen overflow-x-hidden bg-[#070a0f] text-[#edf2f7]"><div className="ambient"/><header className="sticky top-0 z-30 border-b border-white/[0.07] bg-[#070a0f]/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1500px] items-center justify-between gap-3 px-4 sm:px-7"><button type="button" onClick={() => router.push("/")} className="inline-flex min-w-0 cursor-pointer items-center gap-2 rounded-md px-1 py-2 text-sm text-slate-300 hover:text-white focus-visible:outline-2 focus-visible:outline-cyan-300" aria-label="返回 KOL Signal"><ChevronLeft size={17}/><span className="truncate">KOL Signal</span></button><div className="flex items-center gap-2"><span className="rounded-lg border border-cyan-300/20 bg-cyan-300/[0.07] px-2.5 py-1 text-xs text-cyan-200">土狗雷达</span><span className="rounded-lg border border-amber-300/20 bg-amber-300/[0.07] px-2.5 py-1 text-xs text-amber-200">仅模拟交易</span></div></div></header>
    <div className="relative mx-auto max-w-[1500px] px-4 py-6 sm:px-7 sm:py-8"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={<Activity size={18}/>} label="候选总数" value={String(data.totalCandidates)} detail={`当前加载 ${data.rows.length} · 24H新增 ${data.candidates24h}`}/><Summary icon={<Bot size={18}/>} label="AI精选" value={String(data.rows.filter((r) => r.aiDecision === "APPROVE").length)} detail="硬过滤不可被AI绕过"/><Summary icon={<CircleDollarSign size={18}/>} label="Paper持仓" value={String(data.positions.filter((p) => p.status === "open").length)} detail="不签名、不广播"/><Summary icon={<ShieldCheck size={18}/>} label="真实交易" value="关闭" detail="所有主网开关为false"/></section>
      <section className="mt-4 grid gap-3 sm:grid-cols-3"><SourceStatusCard title="Ave Smart 采集器" status={data.aveSmartStatus} detail={data.aveSmartLastHeartbeatAt ? `最后心跳：${formatShanghaiDateTime(data.aveSmartLastHeartbeatAt)} · 捕获 ${String(data.aveCollector?.captured_count ?? 0)} · 上传 ${String(data.aveCollector?.uploaded_count ?? 0)} · 去重 ${String(data.aveCollector?.dedup_count ?? 0)} · 解析失败 ${String(data.aveCollector?.parse_failed_count ?? 0)}` : "尚无真实采集器心跳；状态不会冒充外部端点阻断。"}/><SourceStatusCard title="GMGN API" status={data.gmgnApiHealth.some((item) => item.successes > 0) ? "READY" : "NO_RECENT_SUCCESS"} detail={data.gmgnApiHealth.length ? data.gmgnApiHealth.map((item) => `${item.endpoint} ${item.successes}/${item.calls}`).join(" · ") : "最近24小时无已计量调用"}/><SourceStatusCard title="GMGN 天眼网页" status={data.gmgnTianyanStatus} detail="Cloudflare 403仅代表天眼网页自动化被阻断，不代表GMGN API不可用。"/></section>
      <div className="mt-5 flex min-w-0 flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div className="flex min-w-0 gap-2 overflow-x-auto pb-1">{tabs.map(([key, label]) => <button key={key} onClick={() => setTab(key)} className={`shrink-0 rounded-lg border px-3 py-2 text-xs ${tab === key ? "border-cyan-300/25 bg-cyan-300/[0.09] text-cyan-200" : "border-white/[0.08] bg-white/[0.025] text-slate-400 hover:text-slate-200"}`}>{label}</button>)}</div><label className="flex min-w-0 items-center gap-2 rounded-lg border border-white/[0.08] bg-[#0b1018] px-3"><Search size={15} className="text-slate-600"/><input value={query} onChange={(e) => setQuery(e.target.value)} className="h-10 min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-slate-600" placeholder="搜索代币/合约"/></label></div>
      {tab === "orders" ? <Orders rows={data.paperOrders}/> : tab === "learning" ? <LearningCenter data={data.learning}/> : tab === "strategy" ? <Strategy/> : tab === "wallet" ? <WalletStatus walletLogin={walletLoginEnabled} walletConnect={walletConnectEnabled} autoTrade={autoTradeEnabled}/> : <><section className="mt-4 grid min-w-0 gap-3 xl:grid-cols-2">{rows.length ? rows.map((row) => <RadarCard key={row.id} row={row}/>) : <Empty/>}</section>{data.nextOffset !== null ? <button type="button" disabled={loadingMore} onClick={async () => { setLoadingMore(true); try { const response = await fetch(`/api/radar/signals?offset=${data.nextOffset}&limit=40`, { cache: "no-store" }); if (response.ok) { const next = await response.json() as RadarDashboardData; setData((current) => ({ ...next, rows: [...current.rows, ...next.rows] })); } } finally { setLoadingMore(false); } }} className="mx-auto mt-5 block rounded-lg border border-cyan-300/20 bg-cyan-300/[0.08] px-5 py-2 text-sm text-cyan-200 disabled:opacity-50">{loadingMore ? "加载中…" : "加载更多"}</button> : null}</>}
    </div></main>;
}
function Summary({ icon, label, value, detail }: { icon: React.ReactNode; label: string; value: string; detail: string }) { return <div className="rounded-xl border border-white/[0.07] bg-[#0b1018]/90 p-4"><div className="flex items-center gap-2 text-xs text-slate-500">{icon}{label}</div><div className="mt-2 text-2xl font-semibold">{value}</div><div className="mt-1 text-xs text-slate-600">{detail}</div></div>; }
function SourceStatusCard({ title, status, detail }: { title: string; status: string; detail: string }) { const good = status.startsWith("READY") || status === "CONNECTED"; return <details className="rounded-xl border border-white/[0.08] bg-[#0b1018] p-4"><summary className="cursor-pointer list-none text-sm font-medium"><span className={`mr-2 inline-block h-2 w-2 rounded-full ${good ? "bg-emerald-300" : "bg-amber-300"}`}/>{title}<span className="ml-2 font-mono text-xs text-slate-500">{status}</span></summary><p className="mt-3 text-xs leading-5 text-slate-500">{detail}</p></details>; }
function Empty() { return <div className="xl:col-span-2 rounded-xl border border-dashed border-white/[0.1] px-6 py-14 text-center text-sm text-slate-500">暂无符合当前分类的真实信号。</div>; }
function Orders({ rows }: { rows: Array<Record<string, unknown>> }) { return <section className="mt-4 overflow-hidden rounded-xl border border-white/[0.08] bg-[#0b1018]"><div className="border-b border-white/[0.07] px-4 py-3 text-sm font-medium">模拟交易记录</div>{rows.length ? rows.map((row) => <div key={String(row.id)} className="grid grid-cols-2 gap-2 border-b border-white/[0.05] px-4 py-3 text-xs sm:grid-cols-5"><span>{String(row.side).toUpperCase()} · {String(row.reason)}</span><span>{String(row.status)}</span><span>数量 {String(row.filled_quantity)}/{String(row.requested_quantity)}</span><span>净额 {row.net_usd ? `$${String(row.net_usd)}` : "--"}</span><span className="text-slate-500">{formatShanghaiDateTime(String(row.created_at))}</span></div>) : <Empty/>}</section>; }
function Strategy() { return <section className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><MarketCapSetting/><StatusCard icon={<DatabaseZap size={18}/>} title="发射器安全门" lines={["仅官方程序/工厂白名单可套用profile", "身份、曲线/池、流动性、买卖路径仍是硬门", "不适用的税率/LP/Owner显示N/A"]}/><StatusCard icon={<Bot size={18}/>} title="量化与AI" lines={["叙事、提前量与传播速度为主要评分", "持有人与开发者数据仅作评论标签", "确定性恶意证据仍硬拒绝"]}/></section>; }
function MarketCapSetting() { const [value, setValue] = useState("20M"); const [message, setMessage] = useState("默认 2000 万美元"); async function save() { setMessage("保存中…"); try { const response = await fetch("/api/settings/kol-market-cap", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ value }) }); const payload = await response.json() as { value?: number; error?: string }; setMessage(response.ok ? `已保存 $${Number(payload.value).toLocaleString()}` : payload.error === "admin_required" ? "仅站点所有者可修改" : "输入无效"); } catch { setMessage("保存失败，请重试"); } } return <div className="rounded-xl border border-white/[0.08] bg-[#0b1018] p-5"><div className="flex items-center gap-2 font-medium text-cyan-200"><DatabaseZap size={18}/>KOL市值上限</div><p className="mt-3 text-xs leading-5 text-slate-500">支持数字、20M、1000M、1B。达到上限的候选在AI与通知前停止。</p><div className="mt-3 flex gap-2"><input value={value} onChange={(event) => setValue(event.target.value)} className="h-10 min-w-0 flex-1 rounded-lg border border-white/10 bg-black/20 px-3 text-sm outline-none focus:border-cyan-300/30" aria-label="KOL预警最大市值"/><button type="button" onClick={() => void save()} className="rounded-lg border border-cyan-300/20 bg-cyan-300/[0.08] px-3 text-sm text-cyan-200">保存</button></div><div className="mt-2 text-xs text-slate-600">{message}</div></div>; }
function LearningCenter({ data }: { data: RadarDashboardData["learning"] }) { const latest = data.promptVersions[0]; return <section className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><StatusCard icon={<BookOpenCheck size={18}/>} title="历史样本" lines={[`冻结样本 ${data.sampleCount} · 完整 ${data.completeSampleCount}`, `人工补充案例 ${data.manualCaseCount}`, "输入冻结在首次信号时刻"]}/><StatusCard icon={<Activity size={18}/>} title="收益分组" lines={[`A ${data.groups.A} · B ${data.groups.B}`, `C ${data.groups.C} · D ${data.groups.D}`, `UNKNOWN ${data.groups.UNKNOWN}（样本不足）`]}/><StatusCard icon={<Bot size={18}/>} title="Grok总结" lines={[data.completeSampleCount < 20 ? "样本不足，禁止生成规律" : data.completeSampleCount < 50 ? "仅允许探索性总结" : "可生成候选规则", "证据URL与发布时间必须保存", "当前倍数均标记 UNVERIFIED"]}/><StatusCard icon={<ShieldCheck size={18}/>} title="Prompt版本" lines={[latest ? `最新 ${latest.version} · ${latest.status}` : "暂无规则版本", "候选规则→历史回放→影子验证", "人工发布并保留审计理由"]}/></section>; }
function WalletStatus({ walletLogin, walletConnect, autoTrade }: { walletLogin: boolean; walletConnect: boolean; autoTrade: boolean }) { return <section className="mt-4 grid gap-3 sm:grid-cols-2"><StatusCard icon={<WalletCards size={18}/>} title="身份钱包" lines={[walletConnect ? "只读钱包已开启" : "钱包与自动交易尚未启用，当前仅模拟交易", `钱包签名登录：${walletLogin ? "已开启" : "未开启"}`, "不索取、不保存私钥或助记词"]}/><StatusCard icon={<ShieldCheck size={18}/>} title="在线交易钱包" lines={["托管与KMS：NOT_PROVISIONED", `自动交易：${autoTrade ? "异常：应关闭" : "已关闭"}`, "真实充值、提现、授权、广播：全部禁用"]}/></section>; }
function StatusCard({ icon, title, lines }: { icon: React.ReactNode; title: string; lines: string[] }) { return <div className="rounded-xl border border-white/[0.08] bg-[#0b1018] p-5"><div className="flex items-center gap-2 font-medium text-cyan-200">{icon}{title}</div><ul className="mt-4 space-y-2 text-sm text-slate-400">{lines.map((line) => <li key={line}>· {line}</li>)}</ul></div>; }
