"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Activity, Bot, ChevronLeft, CircleDollarSign, Clock3, DatabaseZap, Search, ShieldCheck, WalletCards } from "lucide-react";
import type { RadarDashboardData, RadarViewRow } from "@/lib/radar/view";
import { chainLabel, chainTone } from "@/lib/chains";
import { formatShanghaiDateTime, formatTokenPrice, formatUsdCompact } from "@/lib/market-format";

const tabs = [
  ["new", "实时新信号"], ["approved", "AI精选"], ["observing", "观察中"], ["bought", "已买入"], ["closed", "已止盈/已清仓"], ["rejected", "被拒绝"], ["orders", "模拟交易记录"], ["strategy", "策略设置"], ["wallet", "钱包与自动交易状态"],
] as const;
type TabKey = typeof tabs[number][0];

function age(created: string | null, now = Date.now()) { if (!created) return "--"; const ms = now - Date.parse(created); if (!Number.isFinite(ms)) return "--"; const min = Math.max(0, Math.floor(ms / 60_000)); return min < 60 ? `${min}分钟` : min < 1440 ? `${Math.floor(min / 60)}小时` : `${Math.floor(min / 1440)}天`; }
function pct(bps: number | null) { return bps === null ? "--" : `${bps >= 0 ? "+" : ""}${(bps / 100).toFixed(2)}%`; }
function sourceState(row: RadarViewRow) { try { const parsed = JSON.parse(row.sourceStatus) as Record<string, string>; return Object.entries(parsed).map(([key, value]) => `${key}: ${value}`).join(" · ") || "--"; } catch { return row.sourceStatus || "--"; } }

function RadarCard({ row }: { row: RadarViewRow }) {
  const decisionTone = row.aiDecision === "APPROVE" ? "text-emerald-300 border-emerald-300/20 bg-emerald-300/[0.07]" : row.aiDecision === "REJECT" || row.aiDecision === "EMERGENCY_CLOSE" ? "text-rose-300 border-rose-300/20 bg-rose-300/[0.07]" : "text-amber-200 border-amber-300/20 bg-amber-300/[0.07]";
  return <article className="min-w-0 overflow-hidden rounded-2xl border border-white/[0.08] bg-[#0b1018]/95 p-4 shadow-[0_18px_50px_rgba(0,0,0,.18)]">
    <div className="flex min-w-0 flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex min-w-0 flex-wrap items-center gap-2"><h3 className="truncate text-base font-semibold text-slate-100">{row.symbol}</h3><span className={`rounded-md border px-2 py-0.5 text-[11px] ${chainTone(row.chain)}`}>{chainLabel(row.chain)}</span><span className="rounded-md border border-cyan-300/15 bg-cyan-300/[0.06] px-2 py-0.5 text-[11px] text-cyan-200">土狗雷达</span></div><p className="mt-1 truncate text-xs text-slate-500">{row.name}</p></div><span className={`rounded-lg border px-2.5 py-1 text-xs font-medium ${decisionTone}`}>{row.aiDecision} · {Math.round(row.aiConfidence * 100)}%</span></div>
    <div className="mt-3 min-w-0 rounded-lg border border-white/[0.06] bg-black/15 px-3 py-2 font-mono text-[11px] text-slate-400"><div className="truncate">Token {row.tokenAddress}</div><div className="mt-1 truncate">Pair {row.pairAddress || "--"}</div></div>
    <div className="mt-3 grid grid-cols-2 gap-x-3 gap-y-2 text-xs sm:grid-cols-4"><Metric label="价格" value={formatTokenPrice(row.price === null ? null : Number(row.price))}/><Metric label="市值" value={row.marketCap === null ? "--" : formatUsdCompact(row.marketCap)}/><Metric label="流动性" value={row.liquidity === null ? "--" : formatUsdCompact(row.liquidity)}/><Metric label="24H成交额" value={row.volume24h === null ? "--" : formatUsdCompact(row.volume24h)}/><Metric label="持币人数" value={row.holders?.toLocaleString() || "--"}/><Metric label="买家/卖家" value={row.buyers === null || row.sellers === null ? "--" : `${row.buyers}/${row.sellers}`}/><Metric label="KOL/聪明钱" value={String(row.smartMoneyCount)}/><Metric label="币龄" value={age(row.poolCreatedAt)}/></div>
    <div className="mt-3 grid grid-cols-4 gap-2"><Score label="安全" value={row.securityScore}/><Score label="叙事" value={row.narrativeScore}/><Score label="动量" value={row.momentumScore}/><Score label="综合" value={row.totalScore}/></div>
    <p className="mt-3 text-sm leading-6 text-slate-300">{row.aiReason}</p>
    {row.rejectReason && <p className="mt-2 line-clamp-2 text-xs leading-5 text-rose-300/80">拒绝/观察原因：{row.rejectReason}</p>}
    <div className="mt-3 grid grid-cols-2 gap-2 border-t border-white/[0.06] pt-3 text-[11px] text-slate-500 sm:grid-cols-4"><span>来源：{row.signalSource}</span><span>类型：{row.signalType}</span><span>发现：{formatShanghaiDateTime(row.firstSeenAt)}</span><span>数据：{row.dataFreshnessMs === null ? "--" : `${Math.round(row.dataFreshnessMs / 1000)}s`}</span></div>
    <div className="mt-2 truncate text-[11px] text-slate-600">源状态：{sourceState(row)}</div>
    <div className="mt-3 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><Metric label="模拟持仓" value={row.paperEntered ? "已进入" : "未进入"}/><Metric label="计划买入" value={row.plannedBuyUsd ? `$${row.plannedBuyUsd}` : "--"}/><Metric label="当前/最高收益" value={`${pct(row.currentReturnBps)} / ${pct(row.maxReturnBps)}`}/><Metric label="止盈/剩余" value={`${row.takeProfitCount} / ${row.remainingPosition || "--"}`}/></div>
  </article>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="min-w-0"><div className="text-[11px] text-slate-600">{label}</div><div className="mt-0.5 truncate text-slate-300">{value}</div></div>; }
function Score({ label, value }: { label: string; value: number }) { return <div className="rounded-lg border border-white/[0.06] bg-white/[0.025] px-2 py-2 text-center"><div className="text-[10px] text-slate-600">{label}</div><div className="mt-0.5 text-sm font-semibold text-cyan-200">{value}</div></div>; }

export default function RadarDashboard({ initial, walletLoginEnabled, autoTradeEnabled, walletConnectEnabled }: { initial: RadarDashboardData; walletLoginEnabled: boolean; autoTradeEnabled: boolean; walletConnectEnabled: boolean }) {
  const [data, setData] = useState(initial); const [tab, setTab] = useState<TabKey>("new"); const [query, setQuery] = useState("");
  useEffect(() => { let active = true; const refresh = async () => { try { const response = await fetch("/api/radar/signals", { cache: "no-store" }); if (response.ok && active) setData(await response.json() as RadarDashboardData); } catch { /* retain last-known-good UI */ } }; const timer = window.setInterval(refresh, 15_000); const visible = () => { if (!document.hidden) void refresh(); }; document.addEventListener("visibilitychange", visible); return () => { active = false; window.clearInterval(timer); document.removeEventListener("visibilitychange", visible); }; }, []);
  const rows = useMemo(() => data.rows.filter((row) => `${row.symbol} ${row.name} ${row.tokenAddress}`.toLowerCase().includes(query.toLowerCase())).filter((row) => tab === "new" ? true : tab === "approved" ? row.aiDecision === "APPROVE" : tab === "observing" ? row.aiDecision === "HOLD" : tab === "rejected" ? row.aiDecision === "REJECT" : tab === "bought" ? row.paperEntered && row.remainingPosition !== "0" : tab === "closed" ? row.paperEntered && row.remainingPosition === "0" : false), [data.rows, query, tab]);
  return <main className="min-h-screen overflow-x-hidden bg-[#070a0f] text-[#edf2f7]"><div className="ambient"/><header className="sticky top-0 z-30 border-b border-white/[0.07] bg-[#070a0f]/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1500px] items-center justify-between gap-3 px-4 sm:px-7"><Link href="/" className="inline-flex min-w-0 items-center gap-2 text-sm text-slate-300 hover:text-white"><ChevronLeft size={17}/><span className="truncate">KOL Signal</span></Link><div className="flex items-center gap-2"><span className="rounded-lg border border-cyan-300/20 bg-cyan-300/[0.07] px-2.5 py-1 text-xs text-cyan-200">土狗雷达</span><span className="rounded-lg border border-amber-300/20 bg-amber-300/[0.07] px-2.5 py-1 text-xs text-amber-200">仅模拟交易</span></div></div></header>
    <div className="relative mx-auto max-w-[1500px] px-4 py-6 sm:px-7 sm:py-8"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={<Activity size={18}/>} label="实时候选" value={String(data.rows.length)} detail="15秒增量刷新"/><Summary icon={<Bot size={18}/>} label="AI精选" value={String(data.rows.filter((r) => r.aiDecision === "APPROVE").length)} detail="硬过滤不可被AI绕过"/><Summary icon={<CircleDollarSign size={18}/>} label="Paper持仓" value={String(data.positions.filter((p) => p.status === "open").length)} detail="不签名、不广播"/><Summary icon={<ShieldCheck size={18}/>} label="真实交易" value="关闭" detail="所有主网开关为false"/></section>
      <div className="mt-4 rounded-xl border border-amber-300/15 bg-amber-300/[0.05] px-4 py-3 text-sm leading-6 text-amber-100">Ave Smart：<span className="font-mono">{data.aveSmartStatus}</span>。官方未提供可验证公开接口，当前候选明确使用{data.usingFallback ? " GMGN KOL聚集备用发现" : " 已持久化的多源雷达信号"}，不伪装为Ave Smart。</div>
      <div className="mt-5 flex min-w-0 flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div className="flex min-w-0 gap-2 overflow-x-auto pb-1">{tabs.map(([key, label]) => <button key={key} onClick={() => setTab(key)} className={`shrink-0 rounded-lg border px-3 py-2 text-xs ${tab === key ? "border-cyan-300/25 bg-cyan-300/[0.09] text-cyan-200" : "border-white/[0.08] bg-white/[0.025] text-slate-400 hover:text-slate-200"}`}>{label}</button>)}</div><label className="flex min-w-0 items-center gap-2 rounded-lg border border-white/[0.08] bg-[#0b1018] px-3"><Search size={15} className="text-slate-600"/><input value={query} onChange={(e) => setQuery(e.target.value)} className="h-10 min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-slate-600" placeholder="搜索代币/合约"/></label></div>
      {tab === "orders" ? <Orders rows={data.paperOrders}/> : tab === "strategy" ? <Strategy/> : tab === "wallet" ? <WalletStatus walletLogin={walletLoginEnabled} walletConnect={walletConnectEnabled} autoTrade={autoTradeEnabled}/> : <section className="mt-4 grid min-w-0 gap-3 xl:grid-cols-2">{rows.length ? rows.map((row) => <RadarCard key={row.id} row={row}/>) : <Empty/>}</section>}
    </div></main>;
}
function Summary({ icon, label, value, detail }: { icon: React.ReactNode; label: string; value: string; detail: string }) { return <div className="rounded-xl border border-white/[0.07] bg-[#0b1018]/90 p-4"><div className="flex items-center gap-2 text-xs text-slate-500">{icon}{label}</div><div className="mt-2 text-2xl font-semibold">{value}</div><div className="mt-1 text-xs text-slate-600">{detail}</div></div>; }
function Empty() { return <div className="xl:col-span-2 rounded-xl border border-dashed border-white/[0.1] px-6 py-14 text-center text-sm text-slate-500">暂无符合当前分类的真实信号。</div>; }
function Orders({ rows }: { rows: Array<Record<string, unknown>> }) { return <section className="mt-4 overflow-hidden rounded-xl border border-white/[0.08] bg-[#0b1018]"><div className="border-b border-white/[0.07] px-4 py-3 text-sm font-medium">模拟交易记录</div>{rows.length ? rows.map((row) => <div key={String(row.id)} className="grid grid-cols-2 gap-2 border-b border-white/[0.05] px-4 py-3 text-xs sm:grid-cols-5"><span>{String(row.side).toUpperCase()} · {String(row.reason)}</span><span>{String(row.status)}</span><span>数量 {String(row.filled_quantity)}/{String(row.requested_quantity)}</span><span>净额 {row.net_usd ? `$${String(row.net_usd)}` : "--"}</span><span className="text-slate-500">{formatShanghaiDateTime(String(row.created_at))}</span></div>) : <Empty/>}</section>; }
function Strategy() { return <section className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><StatusCard icon={<DatabaseZap size={18}/>} title="默认硬过滤" lines={["最低流动性 $25K", "最大价格冲击 10%", "合约权限/税率/LP/集中度必须已验证"]}/><StatusCard icon={<Bot size={18}/>} title="量化与AI" lines={["安全25 · 流动性15 · 聪明钱15", "增长10 · 量价10 · 叙事20 · 开发者5", "AI异常或证据不足默认HOLD"]}/><StatusCard icon={<Clock3 size={18}/>} title="Paper退出" lines={["-50% 净可成交价值清仓", "2x/4x/8x及后续翻倍卖出剩余50%", "最高净可成交价值回撤50%清仓"]}/></section>; }
function WalletStatus({ walletLogin, walletConnect, autoTrade }: { walletLogin: boolean; walletConnect: boolean; autoTrade: boolean }) { return <section className="mt-4 grid gap-3 sm:grid-cols-2"><StatusCard icon={<WalletCards size={18}/>} title="身份钱包" lines={[`钱包签名登录：${walletLogin ? "已开启" : "BLOCKED / 未开启"}`, `Reown只读连接：${walletConnect ? "已开启" : "已关闭"}`, "不索取、不保存私钥或助记词"]}/><StatusCard icon={<ShieldCheck size={18}/>} title="在线交易钱包" lines={["托管与KMS：NOT_PROVISIONED", `自动交易：${autoTrade ? "异常：应关闭" : "已关闭"}`, "真实充值、提现、授权、广播：全部禁用"]}/></section>; }
function StatusCard({ icon, title, lines }: { icon: React.ReactNode; title: string; lines: string[] }) { return <div className="rounded-xl border border-white/[0.08] bg-[#0b1018] p-5"><div className="flex items-center gap-2 font-medium text-cyan-200">{icon}{title}</div><ul className="mt-4 space-y-2 text-sm text-slate-400">{lines.map((line) => <li key={line}>· {line}</li>)}</ul></div>; }
