"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowDownToLine, ArrowLeft, ArrowUpFromLine, Database, RefreshCw, ShieldAlert } from "lucide-react";
export type FlowEvent = { id: number; direction: string; classification: string; amount_usd: number | null; amount: string | number; symbol: string; price_usd: number | null; price_at: string | null; from_address: string | null; to_address: string | null; from_entity: string | null; to_entity: string | null; tx_hash: string; chain: string; from_label_source: string | null; to_label_source: string | null; label_confidence: string; chain_occurred_at: string; discovered_at: string };
export type FlowAggregate = { inflow_usd: number | null; outflow_usd: number | null };
export type FlowHealth = { status: string; last_error?: string | null };
export type FlowPayload = { events: FlowEvent[]; aggregates: FlowAggregate[]; health: FlowHealth[]; window: string; minimumUsd: number; signConvention: string; institutionTradeCoverage: string; fetchedAt: string };
const money = (v: unknown) => Number.isFinite(Number(v)) ? new Intl.NumberFormat("zh-CN", { style: "currency", currency: "USD", notation: "compact", maximumFractionDigits: 2 }).format(Number(v)) : "估值待核实";
const fmt = (v: unknown) => v ? new Intl.DateTimeFormat("zh-CN", { timeZone: "Asia/Shanghai", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false }).format(new Date(String(v))) : "—";
const short = (v: unknown) => { const s = String(v || ""); return s.length > 20 ? `${s.slice(0, 9)}…${s.slice(-7)}` : s || "—"; };

export default function FlowDashboard({ initial }: { initial: FlowPayload }) {
  const [data, setData] = useState(initial); const [window, setWindow] = useState<"1h" | "24h">("24h"); const [symbol, setSymbol] = useState(""); const [chain, setChain] = useState(""); const [exchange, setExchange] = useState(""); const [error, setError] = useState(false);
  useEffect(() => { let active = true; const run = async () => { try { const p = new URLSearchParams({ window }); if (symbol) p.set("symbol", symbol); if (chain) p.set("chain", chain); if (exchange) p.set("exchange", exchange); const r = await fetch(`/api/fund-flows?${p}`, { cache: "no-store" }); if (!r.ok) throw new Error(); const next = await r.json() as FlowPayload; if (active) { setData(next); setError(false); } } catch { if (active) setError(true); } }; void run(); const t = setInterval(run, 15000); return () => { active = false; clearInterval(t); }; }, [window, symbol, chain, exchange]);
  const totals = useMemo(() => data.aggregates.reduce((a, r) => ({ inflow: a.inflow + Number(r.inflow_usd || 0), outflow: a.outflow + Number(r.outflow_usd || 0) }), { inflow: 0, outflow: 0 }), [data.aggregates]); const health = data.health[0]; const coverageBlocked = !health || health.status !== "healthy";
  return <main className="min-h-screen overflow-x-hidden bg-[#070a0f] text-slate-100">
    <header className="sticky top-0 z-30 border-b border-white/10 bg-[#070a0f]/90 backdrop-blur-xl"><div className="mx-auto flex min-h-16 max-w-[1500px] flex-wrap items-center justify-between gap-2 px-4 py-2 sm:px-7"><Link href="/" className="inline-flex items-center gap-2 text-sm text-slate-300"><ArrowLeft size={16}/>KOL Signal</Link><nav className="flex flex-wrap gap-2 text-xs"><Link href="/radar" className="rounded-lg border border-white/10 px-3 py-2 text-slate-400">土狗雷达</Link><Link href="/exchanges" className="rounded-lg border border-white/10 px-3 py-2 text-slate-400">交易所动态</Link><span className="rounded-lg border border-violet-300/20 bg-violet-300/10 px-3 py-2 text-violet-200">大额资金流向</span></nav></div></header>
    <div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-7"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-2xl font-semibold">大额资金流向</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">仅展示单笔估值不少于 1,000 万美元的真实链上转账。转入交易所只标为潜在卖压，提币只标为转出；不把转账推断为已买入或已卖出。</p></div><div className={`inline-flex items-center gap-2 text-xs ${error ? "text-amber-300" : "text-slate-500"}`}><RefreshCw size={13}/>{error ? "刷新失败，保留最近结果" : `自动刷新 · ${fmt(data.fetchedAt)}`}</div></div>
      {coverageBlocked && <section className="mt-5 flex items-start gap-3 rounded-2xl border border-amber-300/20 bg-amber-300/[0.06] p-4 text-sm text-amber-100"><ShieldAlert size={18} className="mt-0.5 shrink-0"/><div><div className="font-medium">资金流实时覆盖不足</div><p className="mt-1 leading-6 text-amber-100/70">{String(health?.last_error || "尚未接入带地址归属和价格的实时资金流服务。WHALE_ALERT_API_KEY 缺失时不会生成假数据或显示零流量。")}</p></div></section>}
      <section className="mt-5 grid gap-3 sm:grid-cols-3"><Metric icon={<ArrowDownToLine size={17}/>} label={`${window} 转入交易所`} value={coverageBlocked ? "覆盖不足" : money(totals.inflow)} tone={coverageBlocked ? "text-amber-200" : "text-red-300"}/><Metric icon={<ArrowUpFromLine size={17}/>} label={`${window} 转出交易所`} value={coverageBlocked ? "覆盖不足" : money(totals.outflow)} tone={coverageBlocked ? "text-amber-200" : "text-emerald-300"}/><Metric icon={<Database size={17}/>} label="净额（流出－流入）" value={coverageBlocked ? "覆盖不足" : money(totals.outflow - totals.inflow)} tone={coverageBlocked ? "text-amber-200" : totals.outflow - totals.inflow >= 0 ? "text-emerald-300" : "text-red-300"}/></section>
      <p className="mt-2 text-xs text-slate-600">{data.signConvention} 机构净买卖为独立指标：{data.institutionTradeCoverage}</p>
      <section className="mt-5 rounded-2xl border border-white/8 bg-[#0b1018]"><div className="grid gap-3 border-b border-white/8 p-4 sm:grid-cols-2 lg:grid-cols-5"><select value={window} onChange={(e) => setWindow(e.target.value as "1h" | "24h")} className="h-10 rounded-xl border border-white/10 bg-[#0b1018] px-3 text-sm"><option value="1h">最近 1 小时</option><option value="24h">最近 24 小时</option></select><input value={symbol} onChange={(e) => setSymbol(e.target.value.toUpperCase())} placeholder="币种，如 BTC / USDT" className="h-10 min-w-0 rounded-xl border border-white/10 bg-black/20 px-3 text-sm outline-none"/><input value={exchange} onChange={(e) => setExchange(e.target.value)} placeholder="交易所或机构" className="h-10 min-w-0 rounded-xl border border-white/10 bg-black/20 px-3 text-sm outline-none"/><input value={chain} onChange={(e) => setChain(e.target.value)} placeholder="链" className="h-10 min-w-0 rounded-xl border border-white/10 bg-black/20 px-3 text-sm outline-none"/><div className="self-center text-xs text-slate-600">门槛 {money(data.minimumUsd)}</div></div>
        <div className="divide-y divide-white/6">{data.events.map((event) => <article key={event.id} className="grid min-w-0 gap-4 p-4 lg:grid-cols-[150px_170px_minmax(0,1fr)_180px]"><div><span className={`rounded-md px-2 py-1 text-xs ${event.direction === "inflow" ? "bg-red-300/10 text-red-300" : event.direction === "outflow" ? "bg-emerald-300/10 text-emerald-300" : "bg-slate-300/10 text-slate-400"}`}>{event.direction === "inflow" ? "转入交易所／潜在卖压" : event.direction === "outflow" ? "转出交易所" : "不计净额"}</span><div className="mt-2 text-xs text-slate-500">{event.classification}</div></div><div><div className="text-lg font-semibold">{money(event.amount_usd)}</div><div className="mt-1 text-xs text-slate-500">{Number(event.amount).toLocaleString("en-US")} {event.symbol}</div><div className="text-xs text-slate-600">价格 {event.price_usd ? money(event.price_usd) : "估值待核实"} · {fmt(event.price_at)}</div></div><div className="min-w-0 space-y-2 text-xs"><Address label="来源" address={event.from_address} entity={event.from_entity}/><Address label="去向" address={event.to_address} entity={event.to_entity}/><div className="break-all text-slate-600">交易哈希 {short(event.tx_hash)}</div></div><div className="space-y-1 text-xs text-slate-500"><div>链：<span className="text-slate-300">{event.chain}</span></div><div>标签：<span className="text-slate-300">{event.from_label_source || event.to_label_source || "归属待核实"}</span></div><div>可信度：<span className="text-slate-300">{event.label_confidence}</span></div><div>链上：<span className="text-slate-300">{fmt(event.chain_occurred_at)}</span></div><div>发现：<span className="text-slate-300">{fmt(event.discovered_at)}</span></div></div></article>)}{!data.events.length && <div className="grid min-h-56 place-items-center p-8 text-center"><div><Database className="mx-auto mb-3 text-slate-700"/><p className="text-slate-300">当前没有可验证的大额资金流事件</p><p className="mt-1 max-w-lg text-sm leading-6 text-slate-600">这可能是所选时间段确实无事件，也可能是覆盖不足；请以上方采集状态为准，不将空结果解释为零流量。</p></div></div>}</div>
      </section>
    </div>
  </main>;
}
function Metric({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: string; tone: string }) { return <div className="rounded-2xl border border-white/8 bg-[#0b1018] p-4"><div className="flex items-center gap-2 text-sm text-slate-500">{icon}{label}</div><div className={`mt-3 text-2xl font-semibold ${tone}`}>{value}</div></div>; }
function Address({ label, address, entity }: { label: string; address: unknown; entity: unknown }) { return <div className="min-w-0"><span className="text-slate-600">{label}：</span><span className="text-slate-300">{String(entity || "归属待核实")}</span><div className="mt-0.5 break-all font-mono text-slate-600 [overflow-wrap:anywhere]">{String(address || "—")}</div></div>; }
