"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowDownToLine, ArrowLeft, ArrowUpFromLine, Database, ExternalLink, RefreshCw, ShieldAlert } from "lucide-react";
export type FlowEvent = { id: number; direction: string; classification: string; token_contract: string | null; raw_amount: string | null; amount_usd: number | null; amount: string | number; symbol: string; price_usd: number | null; price_at: string | null; price_source: string | null; valuation_method: string | null; source_url: string | null; attribution_url: string | null; from_address: string | null; to_address: string | null; from_entity: string | null; to_entity: string | null; tx_hash: string; chain: string; from_label_source: string | null; to_label_source: string | null; label_confidence: string; chain_occurred_at: string; discovered_at: string };
export type MintEvent = { id: number; symbol: string; chain: string; token_contract: string; raw_amount: string; amount: string; amount_usd: number; tx_hash: string; issuer: string; recipient_address: string | null; evidence_type: string; issuance_classification: string; source_url: string; contract_evidence_url: string; chain_occurred_at: string; discovered_at: string };
export type FlowAggregate = { inflow_usd: number | null; outflow_usd: number | null };
export type FlowHealth = { source?: string; status: string; connection_status?: string; last_error?: string | null; coverage_json?: string | null; last_success_at?: string | null; last_heartbeat_at?: string | null };
export type FlowPayload = { events: FlowEvent[]; mintEvents: MintEvent[]; aggregates: FlowAggregate[]; health: FlowHealth[]; recordCount: number; totalVerifiedRecords: number; latestEventAt: string | null; latestDiscoveredAt: string | null; window: string; minimumUsd: number; signConvention: string; institutionTradeCoverage: string; fetchedAt: string };
const money = (v: unknown) => Number.isFinite(Number(v)) ? new Intl.NumberFormat("zh-CN", { style: "currency", currency: "USD", notation: "compact", maximumFractionDigits: 2 }).format(Number(v)) : "估值待核实";
const fmt = (v: unknown) => v ? new Intl.DateTimeFormat("zh-CN", { timeZone: "Asia/Shanghai", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false }).format(new Date(String(v))).replace(/^(\d{2})\/(\d{2})(?:,\s*|\s+)/u, "$1月$2日 ") : "—";
const short = (v: unknown) => { const s = String(v || ""); return s.length > 20 ? `${s.slice(0, 9)}…${s.slice(-7)}` : s || "—"; };
const classificationLabels:Record<string,string>={exchange_inflow:"转入交易所",exchange_outflow:"转出交易所",internal_transfer:"交易所内部划转",same_entity:"同实体地址搬仓",bridge:"跨链桥转移",unclassified:"归属待核实"};
const confidenceLabels:Record<string,string>={official_disclosure:"交易所官方披露",provider_attributed:"供应商已标注",unverified:"待核实",high:"高",medium:"中",low:"低"};
const sourceLabels:Record<string,string>={whale_alert:"Whale Alert",bitquery:"Bitquery",public_rpc:"公开链上 RPC（有限覆盖）"};
const chainLabels:Record<string,string>={ethereum:"以太坊"};
const knownEthereumContracts:Record<string,string>={USDT:"0xdac17f958d2ee523a2206206994597c13d831ec7",USDC:"0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",UNI:"0x1f9840a85d5af5bf1d1762f925bdaddc4201f984"};
function flowHealthMessage(row:FlowHealth){const raw=String(row.last_error||row.connection_status||row.status);if(raw.includes("WHALE_ALERT_API_KEY"))return "Whale Alert 数据源未配置；未启动付费服务";if(raw.includes("公开网页展示")||raw.includes("license"))return "公开网页展示授权尚未确认";if(raw==="not_configured")return "尚未配置";if(raw==="reconnecting")return "正在重新连接";if(raw==="connected"||raw==="healthy")return "正常";return "采集异常";}

export default function FlowDashboard({ initial }: { initial: FlowPayload }) {
  const [data, setData] = useState(initial); const [window, setWindow] = useState<"1h" | "24h">("24h"); const [symbol, setSymbol] = useState(""); const [chain, setChain] = useState(""); const [exchange, setExchange] = useState(""); const [error, setError] = useState(false); const [refreshKey,setRefreshKey]=useState(0);
  useEffect(() => { let active = true; const run = async () => { try { const p = new URLSearchParams({ window }); if (symbol) p.set("symbol", symbol); if (chain) p.set("chain", chain); if (exchange) p.set("exchange", exchange); const r = await fetch(`/api/fund-flows?${p}`, { cache: "no-store" }); if (!r.ok) throw new Error(); const next = await r.json() as FlowPayload; if (active) { setData(next); setError(false); } } catch { if (active) setError(true); } }; void run(); const t = setInterval(run, 15000); return () => { active = false; clearInterval(t); }; }, [window, symbol, chain, exchange,refreshKey]);
  const totals = useMemo(() => data.aggregates.reduce((a, r) => ({ inflow: a.inflow + Number(r.inflow_usd || 0), outflow: a.outflow + Number(r.outflow_usd || 0) }), { inflow: 0, outflow: 0 }), [data.aggregates]); const healthySources = data.health.filter((row) => row.status === "healthy"); const coverageBlocked = healthySources.length === 0; const publicHealth=data.health.find((row)=>row.source==="public_rpc"); const publicCoverage=(()=>{try{return JSON.parse(String(publicHealth?.coverage_json||"[]")) as Array<Record<string,unknown>>}catch{return []}})(); const valuationInsufficientCount=Number(publicCoverage[0]?.valuationInsufficientTransfers||0); const heartbeatAge=publicHealth?.last_heartbeat_at?new Date(data.fetchedAt).getTime()-new Date(publicHealth.last_heartbeat_at).getTime():Number.POSITIVE_INFINITY;const collectorFresh=publicHealth?.status==="healthy"&&heartbeatAge<=180_000;
  return <main className="min-h-screen overflow-x-hidden bg-[#070a0f] text-slate-100">
    <header className="sticky top-0 z-30 border-b border-white/10 bg-[#070a0f]/90 backdrop-blur-xl"><div className="mx-auto flex min-h-16 max-w-[1500px] flex-wrap items-center justify-between gap-2 px-4 py-2 sm:px-7"><Link href="/" className="inline-flex items-center gap-2 text-sm text-slate-300"><ArrowLeft size={16}/>KOL Signal</Link><nav className="flex flex-wrap gap-2 text-xs"><Link href="/radar" className="rounded-lg border border-white/10 px-3 py-2 text-slate-400">土狗雷达</Link><Link href="/exchanges" className="rounded-lg border border-white/10 px-3 py-2 text-slate-400">交易所动态</Link><span className="rounded-lg border border-violet-300/20 bg-violet-300/10 px-3 py-2 text-violet-200">大额资金流向</span></nav></div></header>
    <div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-7"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-2xl font-semibold">大额资金流向</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">仅展示单笔名义估值不少于 1,000 万美元的真实链上转账。转入交易所只标为潜在卖压，提币只标为转出；不把转账推断为已买入或已卖出。本栏目仅在网页展示，不发送企业微信通知。</p></div><button type="button" onClick={()=>setRefreshKey((value)=>value+1)} className={`inline-flex items-center gap-2 text-xs ${error ? "text-amber-300" : "text-slate-500"}`}><RefreshCw size={13}/>{error ? "刷新失败，保留最近结果" : `立即刷新 · ${fmt(data.fetchedAt)}`}</button></div>
      {publicHealth?.status === "healthy" && <section className="mt-5 rounded-2xl border border-violet-300/20 bg-violet-300/[0.06] p-4 text-sm text-violet-100"><div className="font-medium">有限覆盖 · 已知地址样本，不代表交易所全部净流入</div><p className="mt-1 leading-6 text-violet-100/70">当前覆盖以太坊主网的 USDT、USDC 与 UNI。稳定币采用 1 美元名义估值；UNI 仅在对应区块的 Chainlink 价格可核验且单笔达到门槛时展示。</p><p className="mt-1 leading-6 text-violet-100/70">采集状态：<span className={collectorFresh?"text-emerald-300":"text-amber-300"}>{collectorFresh?"持续采集中":"采集心跳已过期"}</span>；最近成功采集：{fmt(publicHealth.last_success_at)}；当前筛选 {data.recordCount} 条；已验证累计 {data.totalVerifiedRecords} 条；最新链上事件：{fmt(data.latestEventAt)}。{valuationInsufficientCount>0&&<span className="text-amber-300"> 本轮有 {valuationInsufficientCount} 笔候选因事件时价格不可核验而标记为估值不足，未入库。</span>}</p><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-5">{publicCoverage.map((row)=><div key={String(row.exchange)} className="min-w-0 rounded-xl border border-white/10 bg-black/10 p-3"><div className="font-medium text-slate-200">{String(row.exchange)}</div><div className="mt-1 text-xs text-slate-400">以太坊 · {Number(row.addressCount||0)} 个地址</div><div className="mt-1 text-xs text-slate-500">币种：{Array.isArray(row.assets)?row.assets.join("、"):"覆盖不足"}</div><div className="mt-1 text-xs text-slate-500">最近采集：{fmt(row.lastCollectedAt)}</div><div className="mt-1 break-words text-xs text-slate-600">{String(row.addressScope||"覆盖不足")}</div></div>)}</div><p className="mt-3 leading-6 text-violet-100/60">遗漏风险：未披露充值地址、未列出的交易所地址、其他链、未配置可靠价格源的资产、合约路由及链下内部账务不在样本内；空结果不等于零流量。Tenderly 匿名公共网关没有公开服务等级保证或固定配额，失败时采集器会保留游标并退避重试。</p></section>}
      {coverageBlocked && <section className="mt-5 flex items-start gap-3 rounded-2xl border border-amber-300/20 bg-amber-300/[0.06] p-4 text-sm text-amber-100"><ShieldAlert size={18} className="mt-0.5 shrink-0"/><div><div className="font-medium">资金流实时覆盖不足 · 暂未接通</div><p className="mt-1 leading-6 text-amber-100/70">Whale Alert 未取得公开再分发授权；Bitquery 适配器已实现但许可闸门默认关闭，尚无真实订阅数据。页面不会把空结果显示成零流量。</p>{data.health.length > 0 && <div className="mt-2 space-y-1 text-xs text-amber-100/60">{data.health.map((row,index) => <div key={`${row.source || "source"}-${index}`}>{sourceLabels[String(row.source)] || row.source || "采集器"}：{flowHealthMessage(row)}</div>)}</div>}</div></section>}
      <section className="mt-5 grid gap-3 sm:grid-cols-3"><Metric icon={<ArrowDownToLine size={17}/>} label={`${window} 已知地址样本转入`} value={coverageBlocked ? "覆盖不足" : money(totals.inflow)} tone={coverageBlocked ? "text-amber-200" : "text-red-300"}/><Metric icon={<ArrowUpFromLine size={17}/>} label={`${window} 已知地址样本转出`} value={coverageBlocked ? "覆盖不足" : money(totals.outflow)} tone={coverageBlocked ? "text-amber-200" : "text-emerald-300"}/><Metric icon={<Database size={17}/>} label="样本净额（流出－流入）" value={coverageBlocked ? "覆盖不足" : money(totals.outflow - totals.inflow)} tone={coverageBlocked ? "text-amber-200" : totals.outflow - totals.inflow >= 0 ? "text-emerald-300" : "text-red-300"}/></section>
      <p className="mt-2 text-xs text-slate-600">{data.signConvention} 机构净买卖为独立指标：{data.institutionTradeCoverage} 页面时间均为北京时间。</p>
      <section className="mt-5 rounded-2xl border border-white/8 bg-[#0b1018]"><div className="grid gap-3 border-b border-white/8 p-4 sm:grid-cols-2 lg:grid-cols-5"><select aria-label="时间范围" value={window} onChange={(e) => setWindow(e.target.value as "1h" | "24h")} className="h-10 rounded-xl border border-white/10 bg-[#0b1018] px-3 text-sm"><option value="1h">最近 1 小时</option><option value="24h">最近 24 小时</option></select><input aria-label="币种筛选" value={symbol} onChange={(e) => setSymbol(e.target.value.toUpperCase())} placeholder="币种，如 BTC / USDT" className="h-10 min-w-0 rounded-xl border border-white/10 bg-black/20 px-3 text-sm outline-none"/><input aria-label="交易所或机构筛选" value={exchange} onChange={(e) => setExchange(e.target.value)} placeholder="交易所或机构" className="h-10 min-w-0 rounded-xl border border-white/10 bg-black/20 px-3 text-sm outline-none"/><input aria-label="链筛选" value={chain} onChange={(e) => setChain(e.target.value)} placeholder="链，如以太坊" className="h-10 min-w-0 rounded-xl border border-white/10 bg-black/20 px-3 text-sm outline-none"/><div className="self-center text-xs text-slate-600">门槛 {money(data.minimumUsd)}</div></div>
        <div className="divide-y divide-white/6">{data.events.map((event) => <article key={event.id} className="grid min-w-0 gap-4 p-4 lg:grid-cols-[150px_170px_minmax(0,1fr)_190px]"><div><span className={`rounded-md px-2 py-1 text-xs ${event.direction === "inflow" ? "bg-red-300/10 text-red-300" : event.direction === "outflow" ? "bg-emerald-300/10 text-emerald-300" : "bg-slate-300/10 text-slate-400"}`}>{event.direction === "inflow" ? "转入交易所／潜在卖压" : event.direction === "outflow" ? "转出交易所" : "不计入净额"}</span><div className="mt-2 text-xs text-slate-500">{classificationLabels[event.classification]||"归属待核实"}</div></div><div><div className="text-lg font-semibold">{money(event.amount_usd)}</div><div className="mt-1 text-xs text-slate-500">{Number(event.amount).toLocaleString("en-US")} {event.symbol}</div><div className="text-xs text-slate-600">{event.valuation_method==="stablecoin_nominal_usd"?"1 美元名义估值":event.price_usd?`事件时价格 ${money(event.price_usd)}`:"估值待核实"} · {fmt(event.price_at)}</div><div className="mt-1 break-all text-xs text-slate-700">合约 {event.token_contract||knownEthereumContracts[event.symbol]||"待核实"}</div></div><div className="min-w-0 space-y-2 text-xs"><Address label="来源" address={event.from_address} entity={event.from_entity}/><Address label="去向" address={event.to_address} entity={event.to_entity}/><div className="break-all text-slate-600">交易哈希 {short(event.tx_hash)}</div><div className="flex flex-wrap gap-3">{event.source_url&&<a href={event.source_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-violet-300">查看链上交易<ExternalLink size={11}/></a>}{event.attribution_url&&<a href={event.attribution_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-violet-300">地址归属依据<ExternalLink size={11}/></a>}</div></div><div className="space-y-1 text-xs text-slate-500"><div>链：<span className="text-slate-300">{chainLabels[event.chain]||"链名称待核实"}</span></div><div>价格来源：<span className="break-all text-slate-300">{event.price_source||(event.valuation_method==="stablecoin_nominal_usd"?"发行方 1 美元锚定名义值":"估值待核实")}</span></div><div>标签出处：<span className="text-slate-300">{event.from_label_source || event.to_label_source || "归属待核实"}</span></div><div>标签可信度：<span className="text-slate-300">{confidenceLabels[event.label_confidence]||"待核实"}</span></div><div>链上发生时间：<span className="text-slate-300">{fmt(event.chain_occurred_at)}</span></div><div>发现时间：<span className="text-slate-300">{fmt(event.discovered_at)}</span></div></div></article>)}{!data.events.length && <div className="grid min-h-56 place-items-center p-8 text-center"><div><Database className="mx-auto mb-3 text-slate-700"/><p className="text-slate-300">当前没有可验证的大额资金流事件</p><p className="mt-1 max-w-lg text-sm leading-6 text-slate-600">这可能是所选时间段确实无事件，也可能是覆盖不足；请以上方采集状态为准，不将空结果解释为零流量。</p></div></div>}</div>
      </section>
      <section className="mt-5 rounded-2xl border border-white/8 bg-[#0b1018]"><div className="border-b border-white/8 p-4"><h2 className="font-medium">近 30 天 USDT / USDC 链上铸造（单笔大于 1 亿美元）</h2><p className="mt-1 text-xs leading-5 text-slate-600">只接受发行方合约的原生铸造事件；不会把普通转账或交易所流入重复记为铸造。链上铸造不等于已进入流通，库存状态未获发行方交易级确认时明确标为待核实。</p></div><div className="divide-y divide-white/6">{data.mintEvents.map((event)=><article key={event.id} className="grid min-w-0 gap-3 p-4 md:grid-cols-[150px_180px_minmax(0,1fr)]"><div><div className="font-semibold text-violet-200">{event.symbol} 链上铸造</div><div className="mt-1 text-xs text-slate-500">库存／流通状态待核实</div></div><div><div className="font-semibold">{money(event.amount_usd)}</div><div className="text-xs text-slate-500">{Number(event.amount).toLocaleString("en-US")} {event.symbol}</div><div className="mt-1 text-xs text-slate-600">发行方：{event.issuer}</div></div><div className="min-w-0 space-y-1 text-xs text-slate-500"><div className="break-all">合约：<span className="text-slate-300">{event.token_contract}</span></div><div className="break-all">接收地址：<span className="text-slate-300">{event.recipient_address||"事件未提供，待核实"}</span></div><div>链上发生时间：<span className="text-slate-300">{fmt(event.chain_occurred_at)}</span></div><div>发现时间：<span className="text-slate-300">{fmt(event.discovered_at)}</span></div><div className="flex flex-wrap gap-3"><a href={event.source_url} target="_blank" rel="noreferrer" className="text-violet-300">查看链上交易</a><a href={event.contract_evidence_url} target="_blank" rel="noreferrer" className="text-violet-300">查看发行方／合约依据</a></div></div></article>)}{!data.mintEvents.length&&<div className="p-8 text-center text-sm text-slate-600">近 30 天没有经合约事件确认且大于 1 亿美元的铸造记录；真实样本仍待验证。</div>}</div></section>
    </div>
  </main>;
}
function Metric({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: string; tone: string }) { return <div className="rounded-2xl border border-white/8 bg-[#0b1018] p-4"><div className="flex items-center gap-2 text-sm text-slate-500">{icon}{label}</div><div className={`mt-3 text-2xl font-semibold ${tone}`}>{value}</div></div>; }
function Address({ label, address, entity }: { label: string; address: unknown; entity: unknown }) { return <div className="min-w-0"><span className="text-slate-600">{label}：</span><span className="text-slate-300">{String(entity || "归属待核实")}</span><div className="mt-0.5 break-all font-mono text-slate-600 [overflow-wrap:anywhere]">{String(address || "—")}</div></div>; }
