import { env } from "cloudflare:workers";
import { EXCHANGES } from "@/lib/exchange-intelligence";
export const dynamic = "force-dynamic";
function safe(value: string | null, allowed: string[]) { return value && allowed.includes(value) ? value : null; }
export async function GET(request: Request) {
  if (!env.DB) return Response.json({ events: [], health: [], coverage: "database_unavailable", fetchedAt: new Date().toISOString() }, { status: 503 });
  const url = new URL(request.url); const exchange = safe(url.searchParams.get("exchange"), [...EXCHANGES]); const type = safe(url.searchParams.get("type"), ["first_spot_listing", "spot_pair_add", "contract_open", "alpha_add", "alpha_remove", "launch_activity", "token_delisting", "pair_delisting"]); const market = safe(url.searchParams.get("market"), ["spot", "contract", "activity", "alpha"]); const status = safe(url.searchParams.get("status"), ["announced", "effective", "cancelled"]); const q = (url.searchParams.get("q") || "").trim().slice(0, 80); const from = url.searchParams.get("from"); const conditions: string[] = []; const binds: unknown[] = [];
  if (exchange) { conditions.push("exchange=?"); binds.push(exchange); } if (type) { conditions.push("event_type=?"); binds.push(type); } if (market) { conditions.push("market_type=?"); binds.push(market); } if (status) { conditions.push("status=?"); binds.push(status); } if (from && Number.isFinite(new Date(from).getTime())) { conditions.push("discovered_at>=?"); binds.push(new Date(from).toISOString()); } if (q) { conditions.push("(title LIKE ? OR assets_json LIKE ? OR pairs_json LIKE ?)"); binds.push(`%${q}%`, `%${q}%`, `%${q}%`); }
  const [rows, health] = await Promise.all([env.DB.prepare(`SELECT * FROM exchange_events ${conditions.length ? `WHERE ${conditions.join(" AND ")}` : ""} ORDER BY COALESCE(announcement_at,discovered_at) DESC,id DESC LIMIT 100`).bind(...binds).all<Record<string, unknown>>(), env.DB.prepare("SELECT * FROM exchange_collector_state ORDER BY exchange,source").all<Record<string, unknown>>()]);
  return Response.json({ events: rows.results.map((row) => ({ ...row, assets: JSON.parse(String(row.assets_json || "[]")), pairs: JSON.parse(String(row.pairs_json || "[]")), assets_json: undefined, pairs_json: undefined })), health: health.results, monitoredExchanges: [...EXCHANGES], rankingClaim: false, fetchedAt: new Date().toISOString() });
}
