import { env } from "cloudflare:workers";
import Link from "next/link";
import { ArrowLeft, ExternalLink, Sparkles, Users } from "lucide-react";
import SignalChart from "./chart";
export const dynamic = "force-dynamic";
function money(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", notation: "compact", maximumFractionDigits: 2 }).format(value || 0); }
export default async function SignalDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const signal = await env.DB.prepare("SELECT * FROM signals WHERE id = ?").bind(Number(id)).first<Record<string, unknown>>();
  if (!signal) return <main className="grid min-h-screen place-items-center bg-[#070a0f] text-slate-300"><div className="text-center"><p>没有找到该预警</p><Link href="/" className="mt-4 inline-block text-cyan-300">返回监控面板</Link></div></main>;
  const posts = await env.DB.prepare("SELECT * FROM hot_posts WHERE signal_id = ? ORDER BY rank").bind(Number(id)).all<Record<string, unknown>>();
  const snapshots = await env.DB.prepare("SELECT holder_count, market_value, captured_at FROM snapshots WHERE chain = ? AND token_address = ? ORDER BY captured_at LIMIT 120").bind(signal.chain, signal.token_address).all<Record<string, unknown>>();
  const chartData = snapshots.results.map((row) => ({ time: new Date(String(row.captured_at)).toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" }), holders: Number(row.holder_count), value: Number(row.market_value) }));
  const wallets = JSON.parse(String(signal.wallet_names_json || "[]")) as string[];
  return <main className="min-h-screen bg-[#070a0f] text-[#edf2f7]"><div className="ambient"/><div className="relative mx-auto max-w-6xl px-4 py-7 sm:px-7"><Link href="/" className="mb-6 inline-flex items-center gap-2 text-sm text-slate-500 transition hover:text-cyan-300"><ArrowLeft size={16}/>返回预警列表</Link>
    <section className="rounded-2xl border border-white/[0.08] bg-[#0b1018]/95 p-5 sm:p-7"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-xl border border-cyan-300/15 bg-cyan-300/[0.08] font-semibold text-cyan-200">{String(signal.symbol).slice(0,2)}</div><div><h1 className="text-2xl font-semibold">{String(signal.name)} <span className="text-slate-500">${String(signal.symbol)}</span></h1><p className="mt-1 break-all font-mono text-xs text-slate-600">{String(signal.token_address)}</p></div></div><div className="rounded-xl border border-cyan-300/15 bg-cyan-300/[0.07] px-4 py-3"><div className="text-xs text-cyan-300/70">当前聚集</div><div className="mt-1 text-xl font-semibold text-cyan-200">{Number(signal.holder_count)} 人</div></div></div>
      <div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4"><Box label="市值" value={money(Number(signal.market_cap))}/><Box label="流动性" value={money(Number(signal.liquidity))}/><Box label="持币地址" value={Number(signal.holders).toLocaleString()}/><Box label="24H交易额" value={money(Number(signal.volume_24h))}/></div>
      <div className="mt-7 rounded-xl border border-cyan-300/10 bg-gradient-to-r from-cyan-300/[0.07] to-violet-400/[0.05] p-5"><div className="flex items-center gap-2 text-sm text-cyan-300"><Sparkles size={16}/>AI分析</div><p className="mt-2 leading-7 text-slate-200">{String(signal.ai_analysis)}</p><p className="mt-3 text-xs text-slate-500">GMGN主题：{String(signal.gmgn_theme)}</p></div>
    </section>
    <section className="mt-5 grid gap-5 lg:grid-cols-[1.65fr_1fr]"><div className="rounded-2xl border border-white/[0.08] bg-[#0b1018]/95 p-5"><div className="mb-2 flex items-center justify-between"><div><h2 className="font-semibold">KOL持仓趋势</h2><p className="mt-1 text-xs text-slate-600">持仓人数与估算总价值</p></div><span className="text-xs text-slate-600">自动更新</span></div>{chartData.length ? <SignalChart data={chartData}/> : <div className="grid h-72 place-items-center text-sm text-slate-600">等待下一轮持仓快照</div>}</div><div className="rounded-2xl border border-white/[0.08] bg-[#0b1018]/95 p-5"><div className="flex items-center gap-2"><Users size={16} className="text-cyan-300"/><h2 className="font-semibold">建仓账户</h2></div><div className="mt-4 flex max-h-72 flex-wrap content-start gap-2 overflow-auto">{wallets.map((name, index) => <span key={`${name}-${index}`} className="rounded-lg border border-white/[0.08] bg-white/[0.03] px-2.5 py-1.5 text-xs text-slate-400">{name}</span>)}</div></div></section>
    <section className="mt-5 rounded-2xl border border-white/[0.08] bg-[#0b1018]/95 p-5 sm:p-6"><div><h2 className="font-semibold">热门评论</h2><p className="mt-1 text-xs text-slate-600">X平台热门原创内容，经AI筛选并翻译</p></div><div className="mt-5 grid gap-3 lg:grid-cols-3">{posts.results.length ? posts.results.map((post) => <a key={String(post.id)} href={String(post.url)} target="_blank" rel="noreferrer" className="group rounded-xl border border-white/[0.08] bg-white/[0.025] p-4 transition hover:border-cyan-300/20"><div className="flex items-center justify-between"><span className="grid h-7 w-7 place-items-center rounded-lg bg-cyan-300/10 text-xs font-semibold text-cyan-300">{Number(post.rank)}</span><ExternalLink size={14} className="text-slate-700 group-hover:text-cyan-300"/></div><p className="mt-4 text-sm leading-6 text-slate-300">{String(post.chinese)}</p><div className="mt-4 flex items-center justify-between text-xs text-slate-600"><span>{String(post.author)}</span><span>{String(post.engagement || "查看原帖")}</span></div></a>) : <div className="col-span-3 rounded-xl border border-dashed border-white/[0.08] py-12 text-center text-sm text-slate-600">本阶段未触发X搜索，或暂时没有有效热门帖子</div>}</div></section>
  </div></main>;
}
function Box({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-4"><div className="text-xs text-slate-600">{label}</div><div className="mt-2 font-medium text-slate-200">{value}</div></div>; }
