import { d1Bindings, d1Integer, d1Json, d1Number, d1Text } from "@/lib/d1-values";
import { decideRadar, RADAR_RULE_VERSION } from "@/lib/radar/policy";
import type { RadarAiReview, RadarCandidate } from "@/lib/radar/types";

const SENSITIVE = /api.?key|secret|authorization|cookie|passphrase|private.?key|mnemonic|seed|signature|signed.?transaction/i;
export function sanitizeRadarSnapshot(value: unknown, depth = 0): unknown {
  if (depth > 6) return "[TRUNCATED]";
  if (Array.isArray(value)) return value.slice(0, 100).map((item) => sanitizeRadarSnapshot(item, depth + 1));
  if (!value || typeof value !== "object") return typeof value === "string" ? value.slice(0, 2_000) : value;
  return Object.fromEntries(Object.entries(value as Record<string, unknown>).filter(([key]) => !SENSITIVE.test(key)).map(([key, item]) => [key, sanitizeRadarSnapshot(item, depth + 1)]));
}

export function normalizedRadarAddress(chain: string, address: string) { return chain === "sol" ? address.trim() : address.trim().toLowerCase(); }

function nullableNumber(value: unknown) { const parsed = Number(value); return value === null || value === undefined || !Number.isFinite(parsed) ? null : parsed; }
function nullableBoolean(value: unknown) { return typeof value === "boolean" ? value : null; }
export function normalizeRadarCandidate(value: unknown): RadarCandidate | null {
  if (!value || typeof value !== "object") return null;
  const row = value as Record<string, unknown>; const chain = String(row.chain || "");
  if (!(["sol", "bsc", "base", "robinhood"] as string[]).includes(chain) || !String(row.tokenAddress || "").trim() || !String(row.source || "").trim() || !String(row.sourceEventId || "").trim()) return null;
  const developerRisk = row.developerRisk === "clear" || row.developerRisk === "known_bad" ? row.developerRisk : "unknown";
  return { source: String(row.source).slice(0, 80), sourceEventId: String(row.sourceEventId).slice(0, 200), chain: chain as RadarCandidate["chain"], tokenAddress: String(row.tokenAddress), pairAddress: row.pairAddress ? String(row.pairAddress) : null, name: String(row.name || "Unknown"), symbol: String(row.symbol || "—"), firstSeenAt: String(row.firstSeenAt || "invalid"), poolCreatedAt: row.poolCreatedAt ? String(row.poolCreatedAt) : null, price: row.price === null || row.price === undefined ? null : String(row.price), marketCap: nullableNumber(row.marketCap), liquidity: nullableNumber(row.liquidity), volume24h: nullableNumber(row.volume24h), holders: nullableNumber(row.holders), buyers: nullableNumber(row.buyers), sellers: nullableNumber(row.sellers), smartMoneyCount: Math.max(0, Math.round(nullableNumber(row.smartMoneyCount) || 0)), dataFetchedAt: String(row.dataFetchedAt || "invalid"), identityVerified: row.identityVerified === true, sellSimulationPassed: nullableBoolean(row.sellSimulationPassed), honeypot: nullableBoolean(row.honeypot), mintable: nullableBoolean(row.mintable), freezable: nullableBoolean(row.freezable), blacklistable: nullableBoolean(row.blacklistable), taxModifiable: nullableBoolean(row.taxModifiable), buyTaxBps: nullableNumber(row.buyTaxBps), sellTaxBps: nullableNumber(row.sellTaxBps), lpLocked: nullableBoolean(row.lpLocked), topHolderPct: nullableNumber(row.topHolderPct), developerRisk, priceImpactBps: nullableNumber(row.priceImpactBps), sourceConflict: row.sourceConflict === true, launchpadId: row.launchpadId ? String(row.launchpadId) : null, launchpadProgram: row.launchpadProgram ? String(row.launchpadProgram) : null, launchpadFactoryVerified: row.launchpadFactoryVerified === true, launchpadPairVerified: row.launchpadPairVerified === true, launchpadBuyPath: row.launchpadBuyPath === true, launchpadSellPath: row.launchpadSellPath === true, rawSnapshot: row.rawSnapshot && typeof row.rawSnapshot === "object" ? row.rawSnapshot as Record<string, unknown> : {} };
}

export async function persistRadarCandidate(db: D1Database, candidateInput: RadarCandidate, ai: RadarAiReview, now = new Date().toISOString()) {
  const candidate = { ...candidateInput, tokenAddress: normalizedRadarAddress(candidateInput.chain, candidateInput.tokenAddress), pairAddress: candidateInput.pairAddress ? normalizedRadarAddress(candidateInput.chain, candidateInput.pairAddress) : null, rawSnapshot: sanitizeRadarSnapshot(candidateInput.rawSnapshot) as Record<string, unknown> };
  const evaluated = decideRadar(candidate, ai, undefined, Date.parse(now));
  const status = evaluated.decision === "APPROVE" ? "approved" : evaluated.decision === "HOLD" ? "observing" : evaluated.decision === "EMERGENCY_CLOSE" ? "emergency_close" : "rejected";
  const sourceStatus = { [candidate.source]: "received", ai: ai.confidence > 0 ? "reviewed" : "fallback_hold" };
  const fetchedAt = Date.parse(candidate.dataFetchedAt);
  const fields = {
    chain: d1Text(candidate.chain), token_address: d1Text(candidate.tokenAddress), pair_address: candidate.pairAddress, name: d1Text(candidate.name, "Unknown").slice(0, 160), symbol: d1Text(candidate.symbol, "—").slice(0, 40), status, signal_type: "candidate", rule_version: RADAR_RULE_VERSION, model_version: ai.model_version,
    first_seen_at: d1Text(candidate.firstSeenAt, now), pool_created_at: candidate.poolCreatedAt, price: d1Text(candidate.price, "0"), market_cap: candidate.marketCap === null ? null : d1Number(candidate.marketCap), liquidity: candidate.liquidity === null ? null : d1Number(candidate.liquidity), volume_24h: candidate.volume24h === null ? null : d1Number(candidate.volume24h), holders: candidate.holders === null ? null : d1Integer(candidate.holders), buyers: candidate.buyers === null ? null : d1Integer(candidate.buyers), sellers: candidate.sellers === null ? null : d1Integer(candidate.sellers), smart_money_count: d1Integer(candidate.smartMoneyCount), security_score: d1Integer(evaluated.score.security), narrative_score: d1Integer(evaluated.score.narrative), momentum_score: d1Integer(evaluated.score.growth + evaluated.score.volumeFit), total_score: d1Integer(evaluated.score.total), ai_decision: evaluated.decision, ai_confidence: d1Number(ai.confidence), ai_reason: d1Text(evaluated.reasons.join("；") || ai.recommended_action).slice(0, 2_000), hard_filter_passed: evaluated.hard.passed ? 1 : 0, reject_reason: evaluated.decision === "APPROVE" ? null : d1Text(evaluated.reasons.join("；")).slice(0, 2_000), data_freshness_ms: Number.isFinite(fetchedAt) ? Math.max(0, Date.parse(now) - fetchedAt) : null, source_status_json: d1Json(sourceStatus), raw_input_json: d1Json(candidate.rawSnapshot), discovered_at: now, updated_at: now,
  };
  await db.prepare(`INSERT INTO radar_signals (chain,token_address,pair_address,name,symbol,status,signal_type,rule_version,model_version,first_seen_at,pool_created_at,price,market_cap,liquidity,volume_24h,holders,buyers,sellers,smart_money_count,security_score,narrative_score,momentum_score,total_score,ai_decision,ai_confidence,ai_reason,hard_filter_passed,reject_reason,data_freshness_ms,source_status_json,raw_input_json,discovered_at,updated_at)
    VALUES (${Object.keys(fields).map(() => "?").join(",")}) ON CONFLICT(chain,token_address) DO UPDATE SET pair_address=COALESCE(excluded.pair_address,radar_signals.pair_address),name=excluded.name,symbol=excluded.symbol,status=excluded.status,rule_version=excluded.rule_version,model_version=excluded.model_version,price=CASE WHEN CAST(excluded.price AS REAL)>0 THEN excluded.price ELSE radar_signals.price END,market_cap=COALESCE(excluded.market_cap,radar_signals.market_cap),liquidity=COALESCE(excluded.liquidity,radar_signals.liquidity),volume_24h=COALESCE(excluded.volume_24h,radar_signals.volume_24h),holders=COALESCE(excluded.holders,radar_signals.holders),buyers=COALESCE(excluded.buyers,radar_signals.buyers),sellers=COALESCE(excluded.sellers,radar_signals.sellers),smart_money_count=MAX(excluded.smart_money_count,radar_signals.smart_money_count),security_score=excluded.security_score,narrative_score=excluded.narrative_score,momentum_score=excluded.momentum_score,total_score=excluded.total_score,ai_decision=excluded.ai_decision,ai_confidence=excluded.ai_confidence,ai_reason=excluded.ai_reason,hard_filter_passed=excluded.hard_filter_passed,reject_reason=excluded.reject_reason,data_freshness_ms=excluded.data_freshness_ms,source_status_json=excluded.source_status_json,raw_input_json=excluded.raw_input_json,updated_at=excluded.updated_at`).bind(...d1Bindings("radar_signals.upsert", fields)).run();
  const row = await db.prepare("SELECT id FROM radar_signals WHERE chain=? AND token_address=?").bind(candidate.chain, candidate.tokenAddress).first<{ id: number }>();
  if (!row) throw new Error("RADAR_SIGNAL_UPSERT_FAILED");
  const id = d1Integer(row.id); const snapshot = d1Json(candidate.rawSnapshot); const summary = d1Json({ source: candidate.source, source_event_id: candidate.sourceEventId, chain: candidate.chain, token_address: candidate.tokenAddress });
  await db.batch([
    db.prepare(`INSERT INTO radar_signal_sources (radar_signal_id,source,source_event_id,source_url,cursor,observed_at,fetched_at,raw_snapshot_json) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(source,source_event_id) DO UPDATE SET radar_signal_id=excluded.radar_signal_id,observed_at=excluded.observed_at,fetched_at=excluded.fetched_at,raw_snapshot_json=excluded.raw_snapshot_json`).bind(id, candidate.source, candidate.sourceEventId, null, null, candidate.firstSeenAt, candidate.dataFetchedAt, snapshot),
    db.prepare(`INSERT INTO radar_signal_snapshots (radar_signal_id,price,market_cap,liquidity,volume_24h,holders,buyers,sellers,source_status_json,captured_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(radar_signal_id,captured_at) DO UPDATE SET price=excluded.price,market_cap=COALESCE(excluded.market_cap,radar_signal_snapshots.market_cap),liquidity=COALESCE(excluded.liquidity,radar_signal_snapshots.liquidity),volume_24h=COALESCE(excluded.volume_24h,radar_signal_snapshots.volume_24h),holders=COALESCE(excluded.holders,radar_signal_snapshots.holders),buyers=COALESCE(excluded.buyers,radar_signal_snapshots.buyers),sellers=COALESCE(excluded.sellers,radar_signal_snapshots.sellers),source_status_json=excluded.source_status_json`).bind(id, candidate.price, candidate.marketCap, candidate.liquidity, candidate.volume24h, candidate.holders, candidate.buyers, candidate.sellers, d1Json(sourceStatus), candidate.dataFetchedAt),
    db.prepare(`INSERT INTO radar_analysis (radar_signal_id,model_version,decision,confidence,narrative_score,risk_score,stage,positive_reasons_json,negative_reasons_json,invalidators_json,recommended_action,evidence_refs_json,input_summary_json,output_json,created_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM radar_analysis WHERE radar_signal_id=? AND model_version=? AND input_summary_json=?)`).bind(id, ai.model_version, evaluated.decision, ai.confidence, ai.narrative_score, ai.risk_score, ai.stage, d1Json(ai.positive_reasons), d1Json(ai.negative_reasons), d1Json(ai.invalidators), ai.recommended_action, d1Json(ai.evidence_refs), summary, d1Json(ai), now, id, ai.model_version, summary),
  ]);
  if (evaluated.decision === "APPROVE") {
    await db.prepare(`INSERT INTO signals (chain,token_address,name,symbol,threshold,holder_count,market_cap,liquidity,holders,volume_24h,price,gmgn_theme,official_description,ai_analysis,wallet_names_json,alerted_at,alert_status,alert_payload_json,signal_origin,radar_signal_id,radar_score)
      VALUES (?,?,?,?,0,?,?,?,?,?,?,?,'',?,'[]',?,'radar_visible','','radar',?,?)
      ON CONFLICT(chain,token_address,threshold) DO UPDATE SET name=excluded.name,symbol=excluded.symbol,holder_count=MAX(signals.holder_count,excluded.holder_count),market_cap=CASE WHEN excluded.market_cap>0 THEN excluded.market_cap ELSE signals.market_cap END,liquidity=CASE WHEN excluded.liquidity>0 THEN excluded.liquidity ELSE signals.liquidity END,holders=CASE WHEN excluded.holders>0 THEN excluded.holders ELSE signals.holders END,volume_24h=CASE WHEN excluded.volume_24h>0 THEN excluded.volume_24h ELSE signals.volume_24h END,price=CASE WHEN CAST(excluded.price AS REAL)>0 THEN excluded.price ELSE signals.price END,gmgn_theme=excluded.gmgn_theme,ai_analysis=excluded.ai_analysis,alert_status='radar_visible',signal_origin='radar',radar_signal_id=excluded.radar_signal_id,radar_score=excluded.radar_score`).bind(candidate.chain, candidate.tokenAddress, candidate.name, candidate.symbol, candidate.smartMoneyCount, d1Integer(candidate.marketCap), d1Integer(candidate.liquidity), d1Integer(candidate.holders), d1Integer(candidate.volume24h), d1Text(candidate.price, "0"), `土狗雷达 · ${candidate.source}`, d1Text(ai.recommended_action || evaluated.reasons.join("；")).slice(0, 1_200), candidate.firstSeenAt, id, d1Integer(evaluated.score.total)).run();
  }
  return { id, status, decision: evaluated.decision, score: evaluated.score.total, hardFilterPassed: evaluated.hard.passed };
}
