import { d1Bindings, d1Integer, d1Json, d1Number, d1Text } from "@/lib/d1-values";
import { normalizeDexLabel, normalizeVerifiedRadarAddress } from "@/lib/radar/identity";
import { RADAR_PROMPT_VERSION } from "@/lib/radar/ai";
import { decideRadar, RADAR_RULE_VERSION } from "@/lib/radar/policy";
import type { RadarAiReview, RadarCandidate, TradeEligibility } from "@/lib/radar/types";

const SENSITIVE = /api.?key|secret|authorization|cookie|passphrase|private.?key|mnemonic|seed|signature|signed.?transaction/i;
export function sanitizeRadarSnapshot(value: unknown, depth = 0): unknown {
  if (depth > 6) return "[TRUNCATED]";
  if (Array.isArray(value)) return value.slice(0, 100).map((item) => sanitizeRadarSnapshot(item, depth + 1));
  if (!value || typeof value !== "object") return typeof value === "string" ? value.slice(0, 2_000) : value;
  return Object.fromEntries(Object.entries(value as Record<string, unknown>).filter(([key]) => !SENSITIVE.test(key)).map(([key, item]) => [key, sanitizeRadarSnapshot(item, depth + 1)]));
}

export function normalizedRadarAddress(chain: string, address: string) { return chain === "sol" ? address.trim() : address.trim().toLowerCase(); }
function nullableNumber(value: unknown) { const parsed = Number(value); return value === null || value === undefined || !Number.isFinite(parsed) ? null : parsed; }
function nullableBoolean(value: unknown) { return typeof value === "boolean" ? value : null; }

export function normalizeRadarCandidate(value: unknown): RadarCandidate | null {
  if (!value || typeof value !== "object") return null;
  const row = value as Record<string, unknown>; const chain = String(row.chain || "");
  if (!("sol,bsc,base,robinhood".split(",")).includes(chain) || !String(row.tokenAddress || "").trim() || !String(row.source || "").trim() || !String(row.sourceEventId || "").trim()) return null;
  const developerRisk = row.developerRisk === "clear" || row.developerRisk === "known_bad" ? row.developerRisk : "unknown";
  const rawPair = row.pairAddress ? String(row.pairAddress) : null;
  const pairAddress = normalizeVerifiedRadarAddress(chain, rawPair);
  const sourcePairLabel = row.sourcePairLabel ? String(row.sourcePairLabel) : rawPair && !pairAddress ? rawPair : null;
  return {
    source: String(row.source).slice(0, 80), sourceEventId: String(row.sourceEventId).slice(0, 200), chain: chain as RadarCandidate["chain"], tokenAddress: String(row.tokenAddress), pairAddress,
    dexId: normalizeDexLabel(row.dexId) || normalizeDexLabel(sourcePairLabel), routerId: row.routerId ? String(row.routerId).slice(0, 120) : null, launchpadId: row.launchpadId ? String(row.launchpadId).slice(0, 120) : null, factoryAddress: normalizeVerifiedRadarAddress(chain, row.factoryAddress), sourcePairLabel: sourcePairLabel ? sourcePairLabel.slice(0, 120) : null,
    name: String(row.name || "Unknown"), symbol: String(row.symbol || "—"), firstSeenAt: String(row.firstSeenAt || "invalid"), poolCreatedAt: row.poolCreatedAt ? String(row.poolCreatedAt) : null, price: row.price === null || row.price === undefined ? null : String(row.price), marketCap: nullableNumber(row.marketCap), liquidity: nullableNumber(row.liquidity), volume24h: nullableNumber(row.volume24h), holders: nullableNumber(row.holders), buyers: nullableNumber(row.buyers), sellers: nullableNumber(row.sellers), smartMoneyCount: Math.max(0, Math.round(nullableNumber(row.smartMoneyCount) || 0)), dataFetchedAt: String(row.dataFetchedAt || "invalid"), identityVerified: row.identityVerified === true,
    sellSimulationPassed: nullableBoolean(row.sellSimulationPassed), honeypot: nullableBoolean(row.honeypot), mintable: nullableBoolean(row.mintable), freezable: nullableBoolean(row.freezable), blacklistable: nullableBoolean(row.blacklistable), taxModifiable: nullableBoolean(row.taxModifiable), buyTaxBps: nullableNumber(row.buyTaxBps), sellTaxBps: nullableNumber(row.sellTaxBps), lpLocked: nullableBoolean(row.lpLocked), topHolderPct: nullableNumber(row.topHolderPct), developerRisk, priceImpactBps: nullableNumber(row.priceImpactBps), sourceConflict: row.sourceConflict === true,
    launchpadProgram: row.launchpadProgram ? String(row.launchpadProgram) : null, launchpadFactoryVerified: nullableBoolean(row.launchpadFactoryVerified) ?? undefined, launchpadPairVerified: nullableBoolean(row.launchpadPairVerified) ?? undefined, launchpadBuyPath: nullableBoolean(row.launchpadBuyPath) ?? undefined, launchpadSellPath: nullableBoolean(row.launchpadSellPath) ?? undefined,
    rawSnapshot: row.rawSnapshot && typeof row.rawSnapshot === "object" ? row.rawSnapshot as Record<string, unknown> : {},
  };
}

export function narrativeTaskId(signalId: number, candidate: RadarCandidate, review: RadarAiReview) {
  return `${signalId}:${review.prompt_version}:${candidate.firstSeenAt}`.slice(0, 300);
}

function jsonArray<T>(value: unknown): T[] { try { const parsed = JSON.parse(String(value || "[]")); return Array.isArray(parsed) ? parsed as T[] : []; } catch { return []; } }
export async function loadTerminalRadarNarrative(db: D1Database, candidate: RadarCandidate): Promise<RadarAiReview | null> {
  const row = await db.prepare(`SELECT n.* FROM radar_signals r JOIN radar_narrative_analysis n ON n.radar_signal_id=r.id WHERE r.chain=? AND r.token_address=? AND n.prompt_version=? AND n.status IN ('COMPLETED','INSUFFICIENT_EVIDENCE','FAILED') ORDER BY n.updated_at DESC LIMIT 1`).bind(candidate.chain, normalizedRadarAddress(candidate.chain, candidate.tokenAddress), RADAR_PROMPT_VERSION).first<Record<string, unknown>>();
  if (!row) return null;
  return {
    status: String(row.status) as RadarAiReview["status"], decision: String(row.decision || "HOLD") as RadarAiReview["decision"], confidence: Number(row.confidence || 0), narrative_score: row.score === null ? null : Number(row.score), risk_score: row.risk_score === null ? null : Number(row.risk_score), stage: String(row.stage || "unknown"), summary: String(row.summary || ""), freshness_score: row.freshness_score === null ? null : Number(row.freshness_score), sentiment_score: row.sentiment_score === null ? null : Number(row.sentiment_score), lead_score: row.lead_score === null ? null : Number(row.lead_score), positive_reasons: jsonArray<string>(row.positive_reasons_json), negative_reasons: jsonArray<string>(row.negative_reasons_json), invalidators: jsonArray<string>(row.invalidators_json), recommended_action: String(row.recommended_action || "HOLD"), model_version: String(row.model_version), evidence_refs: jsonArray<{ url?: string }>(row.evidence_json).flatMap((item) => item.url ? [item.url] : []), evidence: jsonArray<RadarAiReview["evidence"][number]>(row.evidence_json), prompt_version: String(row.prompt_version), input_cutoff_at: String(row.input_cutoff_at), analysis_at: row.analysis_at ? String(row.analysis_at) : null, attempt_count: Number(row.attempt_count || 0), error_code: row.error_code ? String(row.error_code) : null, input_tokens: row.input_tokens === null ? null : Number(row.input_tokens), output_tokens: row.output_tokens === null ? null : Number(row.output_tokens), cost_microusd: row.cost_microusd === null ? null : Number(row.cost_microusd),
  };
}

export async function persistRadarNarrative(db: D1Database, signalId: number, candidate: RadarCandidate, review: RadarAiReview, now: string) {
  const taskId = narrativeTaskId(signalId, candidate, review);
  const inputSummary = d1Json({ source: candidate.source, source_event_id: candidate.sourceEventId, chain: candidate.chain, token_address: candidate.tokenAddress, symbol: candidate.symbol, source_narrative: candidate.name, input_cutoff_at: candidate.firstSeenAt });
  await db.prepare(`INSERT INTO radar_narrative_analysis (radar_signal_id,task_id,status,prompt_version,model_version,decision,score,risk_score,freshness_score,sentiment_score,lead_score,stage,confidence,summary,positive_reasons_json,negative_reasons_json,invalidators_json,recommended_action,evidence_json,evidence_count,input_summary_json,input_cutoff_at,analysis_at,attempt_count,error_code,input_tokens,output_tokens,cost_microusd,created_at,updated_at)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
    ON CONFLICT(task_id) DO UPDATE SET status=CASE WHEN radar_narrative_analysis.status='COMPLETED' THEN radar_narrative_analysis.status ELSE excluded.status END,model_version=excluded.model_version,decision=CASE WHEN radar_narrative_analysis.status='COMPLETED' THEN radar_narrative_analysis.decision ELSE excluded.decision END,score=CASE WHEN radar_narrative_analysis.status='COMPLETED' THEN radar_narrative_analysis.score ELSE excluded.score END,risk_score=CASE WHEN radar_narrative_analysis.status='COMPLETED' THEN radar_narrative_analysis.risk_score ELSE excluded.risk_score END,freshness_score=CASE WHEN radar_narrative_analysis.status='COMPLETED' THEN radar_narrative_analysis.freshness_score ELSE excluded.freshness_score END,sentiment_score=CASE WHEN radar_narrative_analysis.status='COMPLETED' THEN radar_narrative_analysis.sentiment_score ELSE excluded.sentiment_score END,lead_score=CASE WHEN radar_narrative_analysis.status='COMPLETED' THEN radar_narrative_analysis.lead_score ELSE excluded.lead_score END,stage=CASE WHEN radar_narrative_analysis.status='COMPLETED' THEN radar_narrative_analysis.stage ELSE excluded.stage END,confidence=CASE WHEN radar_narrative_analysis.status='COMPLETED' THEN radar_narrative_analysis.confidence ELSE excluded.confidence END,summary=CASE WHEN radar_narrative_analysis.status='COMPLETED' THEN radar_narrative_analysis.summary ELSE excluded.summary END,positive_reasons_json=CASE WHEN radar_narrative_analysis.status='COMPLETED' THEN radar_narrative_analysis.positive_reasons_json ELSE excluded.positive_reasons_json END,negative_reasons_json=CASE WHEN radar_narrative_analysis.status='COMPLETED' THEN radar_narrative_analysis.negative_reasons_json ELSE excluded.negative_reasons_json END,invalidators_json=CASE WHEN radar_narrative_analysis.status='COMPLETED' THEN radar_narrative_analysis.invalidators_json ELSE excluded.invalidators_json END,recommended_action=CASE WHEN radar_narrative_analysis.status='COMPLETED' THEN radar_narrative_analysis.recommended_action ELSE excluded.recommended_action END,evidence_json=CASE WHEN radar_narrative_analysis.status='COMPLETED' THEN radar_narrative_analysis.evidence_json ELSE excluded.evidence_json END,evidence_count=CASE WHEN radar_narrative_analysis.status='COMPLETED' THEN radar_narrative_analysis.evidence_count ELSE excluded.evidence_count END,analysis_at=CASE WHEN radar_narrative_analysis.status='COMPLETED' THEN radar_narrative_analysis.analysis_at ELSE excluded.analysis_at END,attempt_count=MAX(radar_narrative_analysis.attempt_count,excluded.attempt_count),error_code=CASE WHEN radar_narrative_analysis.status='COMPLETED' THEN radar_narrative_analysis.error_code ELSE excluded.error_code END,input_tokens=COALESCE(excluded.input_tokens,radar_narrative_analysis.input_tokens),output_tokens=COALESCE(excluded.output_tokens,radar_narrative_analysis.output_tokens),cost_microusd=COALESCE(excluded.cost_microusd,radar_narrative_analysis.cost_microusd),updated_at=excluded.updated_at`)
    .bind(signalId, taskId, review.status, review.prompt_version, review.model_version, review.decision, review.narrative_score, review.risk_score, review.freshness_score, review.sentiment_score, review.lead_score, review.stage, review.confidence, review.summary, d1Json(review.positive_reasons), d1Json(review.negative_reasons), d1Json(review.invalidators), review.recommended_action, d1Json(review.evidence), review.evidence.length, inputSummary, review.input_cutoff_at || candidate.firstSeenAt, review.analysis_at, review.attempt_count, review.error_code, review.input_tokens, review.output_tokens, review.cost_microusd, now, now).run();
  await db.prepare(`UPDATE radar_signals SET narrative_status=?,narrative_score_v2=?,narrative_summary=?,narrative_updated_at=?,model_version=?,ai_confidence=?,ai_reason=?,updated_at=? WHERE id=?`)
    .bind(review.status, review.status === "COMPLETED" ? review.narrative_score : null, review.summary, review.analysis_at, review.model_version, review.confidence, review.summary, now, signalId).run();
}

async function persistTradeEligibility(db: D1Database, signalId: number, trade: TradeEligibility, now: string) {
  await db.prepare(`INSERT INTO radar_trade_eligibility (radar_signal_id,status,identity_status,short_reason,checks_json,risk_comments_json,updated_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(radar_signal_id) DO UPDATE SET status=excluded.status,identity_status=excluded.identity_status,short_reason=excluded.short_reason,checks_json=excluded.checks_json,risk_comments_json=excluded.risk_comments_json,updated_at=excluded.updated_at`)
    .bind(signalId, trade.status, trade.identityStatus, trade.shortReason, d1Json(trade.checks), d1Json(trade.riskComments), now).run();
}

export async function persistRadarCandidate(db: D1Database, candidateInput: RadarCandidate, ai: RadarAiReview, now = new Date().toISOString()) {
  const candidate = { ...candidateInput, tokenAddress: normalizedRadarAddress(candidateInput.chain, candidateInput.tokenAddress), pairAddress: normalizeVerifiedRadarAddress(candidateInput.chain, candidateInput.pairAddress), rawSnapshot: sanitizeRadarSnapshot(candidateInput.rawSnapshot) as Record<string, unknown> };
  const evaluated = decideRadar(candidate, ai, undefined, Date.parse(now));
  const status = evaluated.decision === "APPROVE" ? "approved" : evaluated.decision === "REJECT" ? "rejected" : "observing";
  const shortReason = evaluated.hard.status === "PASS" ? "交易检查通过" : evaluated.hard.status === "FAIL" ? `交易拒绝：${evaluated.hard.reasons.slice(0, 2).join("、")}` : `交易暂缓：${evaluated.hard.reasons.slice(0, 2).join("、") || "交易条件待补全"}`;
  const trade: TradeEligibility = { status: evaluated.hard.status, identityStatus: evaluated.hard.identityStatus, shortReason, checks: evaluated.hard.checks, riskComments: evaluated.hard.riskComments };
  const sourceStatus = { [candidate.source]: "received", narrative: ai.status, trade: trade.status };
  const fetchedAt = Date.parse(candidate.dataFetchedAt);
  const fields = {
    chain: d1Text(candidate.chain), token_address: d1Text(candidate.tokenAddress), pair_address: candidate.pairAddress, dex_id: candidate.dexId || null, router_id: candidate.routerId || null, launchpad_id: candidate.launchpadId || null, factory_address: candidate.factoryAddress || null, source_pair_label: candidate.sourcePairLabel || null, identity_status: trade.identityStatus,
    name: d1Text(candidate.name, "Unknown").slice(0, 160), symbol: d1Text(candidate.symbol, "—").slice(0, 40), status, signal_type: "candidate", rule_version: RADAR_RULE_VERSION, model_version: ai.model_version,
    first_seen_at: d1Text(candidate.firstSeenAt, now), pool_created_at: candidate.poolCreatedAt, price: d1Text(candidate.price, "0"), market_cap: candidate.marketCap === null ? null : d1Number(candidate.marketCap), liquidity: candidate.liquidity === null ? null : d1Number(candidate.liquidity), volume_24h: candidate.volume24h === null ? null : d1Number(candidate.volume24h), holders: candidate.holders === null ? null : d1Integer(candidate.holders), buyers: candidate.buyers === null ? null : d1Integer(candidate.buyers), sellers: candidate.sellers === null ? null : d1Integer(candidate.sellers), smart_money_count: d1Integer(candidate.smartMoneyCount), security_score: d1Integer(evaluated.score.security), narrative_score: ai.status === "COMPLETED" && ai.narrative_score !== null ? d1Integer(ai.narrative_score) : 0, narrative_score_v2: ai.status === "COMPLETED" ? ai.narrative_score : null, narrative_status: ai.status, narrative_summary: ai.summary, narrative_updated_at: ai.analysis_at, momentum_score: d1Integer(evaluated.score.growth + evaluated.score.volumeFit), total_score: d1Integer(evaluated.score.total), ai_decision: ai.decision, ai_confidence: d1Number(ai.confidence), ai_reason: d1Text(ai.summary).slice(0, 2_000), hard_filter_passed: evaluated.hard.passed ? 1 : 0, reject_reason: evaluated.hard.status === "FAIL" ? d1Text(evaluated.hard.reasons.join("；")).slice(0, 2_000) : null, data_freshness_ms: Number.isFinite(fetchedAt) ? Math.max(0, Date.parse(now) - fetchedAt) : null, source_status_json: d1Json(sourceStatus), raw_input_json: d1Json(candidate.rawSnapshot), discovered_at: now, updated_at: now,
  };
  await db.prepare(`INSERT INTO radar_signals (${Object.keys(fields).join(",")}) VALUES (${Object.keys(fields).map(() => "?").join(",")}) ON CONFLICT(chain,token_address) DO UPDATE SET pair_address=COALESCE(excluded.pair_address,radar_signals.pair_address),dex_id=COALESCE(excluded.dex_id,radar_signals.dex_id),router_id=COALESCE(excluded.router_id,radar_signals.router_id),launchpad_id=COALESCE(excluded.launchpad_id,radar_signals.launchpad_id),factory_address=COALESCE(excluded.factory_address,radar_signals.factory_address),source_pair_label=COALESCE(excluded.source_pair_label,radar_signals.source_pair_label),identity_status=excluded.identity_status,name=excluded.name,symbol=excluded.symbol,status=excluded.status,rule_version=excluded.rule_version,model_version=excluded.model_version,price=CASE WHEN CAST(excluded.price AS REAL)>0 THEN excluded.price ELSE radar_signals.price END,market_cap=COALESCE(excluded.market_cap,radar_signals.market_cap),liquidity=COALESCE(excluded.liquidity,radar_signals.liquidity),volume_24h=COALESCE(excluded.volume_24h,radar_signals.volume_24h),holders=COALESCE(excluded.holders,radar_signals.holders),buyers=COALESCE(excluded.buyers,radar_signals.buyers),sellers=COALESCE(excluded.sellers,radar_signals.sellers),smart_money_count=MAX(excluded.smart_money_count,radar_signals.smart_money_count),security_score=excluded.security_score,narrative_score=CASE WHEN excluded.narrative_status='COMPLETED' THEN excluded.narrative_score ELSE radar_signals.narrative_score END,narrative_score_v2=CASE WHEN excluded.narrative_status='COMPLETED' THEN excluded.narrative_score_v2 ELSE radar_signals.narrative_score_v2 END,narrative_status=CASE WHEN radar_signals.narrative_status='COMPLETED' THEN radar_signals.narrative_status ELSE excluded.narrative_status END,narrative_summary=CASE WHEN radar_signals.narrative_status='COMPLETED' THEN radar_signals.narrative_summary ELSE excluded.narrative_summary END,narrative_updated_at=CASE WHEN radar_signals.narrative_status='COMPLETED' THEN radar_signals.narrative_updated_at ELSE excluded.narrative_updated_at END,momentum_score=excluded.momentum_score,total_score=excluded.total_score,ai_decision=excluded.ai_decision,ai_confidence=excluded.ai_confidence,ai_reason=excluded.ai_reason,hard_filter_passed=excluded.hard_filter_passed,reject_reason=excluded.reject_reason,data_freshness_ms=excluded.data_freshness_ms,source_status_json=excluded.source_status_json,raw_input_json=excluded.raw_input_json,updated_at=excluded.updated_at`).bind(...d1Bindings("radar_signals.upsert", fields)).run();
  const row = await db.prepare("SELECT id FROM radar_signals WHERE chain=? AND token_address=?").bind(candidate.chain, candidate.tokenAddress).first<{ id: number }>();
  if (!row) throw new Error("RADAR_SIGNAL_UPSERT_FAILED");
  const id = d1Integer(row.id); const snapshot = d1Json(candidate.rawSnapshot);
  await db.batch([
    db.prepare(`INSERT INTO radar_signal_sources (radar_signal_id,source,source_event_id,source_url,cursor,observed_at,fetched_at,raw_snapshot_json) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(source,source_event_id) DO UPDATE SET radar_signal_id=excluded.radar_signal_id,observed_at=excluded.observed_at,fetched_at=excluded.fetched_at,raw_snapshot_json=excluded.raw_snapshot_json`).bind(id, candidate.source, candidate.sourceEventId, null, null, candidate.firstSeenAt, candidate.dataFetchedAt, snapshot),
    db.prepare(`INSERT INTO radar_signal_snapshots (radar_signal_id,price,market_cap,liquidity,volume_24h,holders,buyers,sellers,source_status_json,captured_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(radar_signal_id,captured_at) DO UPDATE SET price=excluded.price,market_cap=COALESCE(excluded.market_cap,radar_signal_snapshots.market_cap),liquidity=COALESCE(excluded.liquidity,radar_signal_snapshots.liquidity),volume_24h=COALESCE(excluded.volume_24h,radar_signal_snapshots.volume_24h),holders=COALESCE(excluded.holders,radar_signal_snapshots.holders),buyers=COALESCE(excluded.buyers,radar_signal_snapshots.buyers),sellers=COALESCE(excluded.sellers,radar_signal_snapshots.sellers),source_status_json=excluded.source_status_json`).bind(id, candidate.price, candidate.marketCap, candidate.liquidity, candidate.volume24h, candidate.holders, candidate.buyers, candidate.sellers, d1Json(sourceStatus), candidate.dataFetchedAt),
  ]);
  await Promise.all([persistTradeEligibility(db, id, trade, now), persistRadarNarrative(db, id, candidate, ai, now)]);
  if (ai.status === "COMPLETED") {
    const summary = d1Json({ source: candidate.source, source_event_id: candidate.sourceEventId, chain: candidate.chain, token_address: candidate.tokenAddress, input_cutoff_at: candidate.firstSeenAt });
    await db.prepare(`INSERT INTO radar_analysis (radar_signal_id,model_version,decision,confidence,narrative_score,risk_score,stage,positive_reasons_json,negative_reasons_json,invalidators_json,recommended_action,evidence_refs_json,input_summary_json,output_json,created_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM radar_analysis WHERE radar_signal_id=? AND model_version=? AND input_summary_json=?)`).bind(id, ai.model_version, ai.decision, ai.confidence, ai.narrative_score, ai.risk_score, ai.stage, d1Json(ai.positive_reasons), d1Json(ai.negative_reasons), d1Json(ai.invalidators), ai.recommended_action, d1Json(ai.evidence_refs), summary, d1Json({ ...ai, evidence: ai.evidence }), now, id, ai.model_version, summary).run();
  }
  if (evaluated.decision === "APPROVE") {
    await db.prepare(`INSERT INTO signals (chain,token_address,name,symbol,threshold,holder_count,market_cap,liquidity,holders,volume_24h,price,gmgn_theme,official_description,ai_analysis,wallet_names_json,alerted_at,alert_status,alert_payload_json,signal_origin,radar_signal_id,radar_score) VALUES (?,?,?,?,0,?,?,?,?,?,?,?,'',?,'[]',?,'radar_visible','','radar',?,?) ON CONFLICT(chain,token_address,threshold) DO UPDATE SET name=excluded.name,symbol=excluded.symbol,holder_count=MAX(signals.holder_count,excluded.holder_count),market_cap=CASE WHEN excluded.market_cap>0 THEN excluded.market_cap ELSE signals.market_cap END,liquidity=CASE WHEN excluded.liquidity>0 THEN excluded.liquidity ELSE signals.liquidity END,holders=CASE WHEN excluded.holders>0 THEN excluded.holders ELSE signals.holders END,volume_24h=CASE WHEN excluded.volume_24h>0 THEN excluded.volume_24h ELSE signals.volume_24h END,price=CASE WHEN CAST(excluded.price AS REAL)>0 THEN excluded.price ELSE signals.price END,gmgn_theme=excluded.gmgn_theme,ai_analysis=excluded.ai_analysis,alert_status='radar_visible',signal_origin='radar',radar_signal_id=excluded.radar_signal_id,radar_score=excluded.radar_score`).bind(candidate.chain, candidate.tokenAddress, candidate.name, candidate.symbol, candidate.smartMoneyCount, d1Integer(candidate.marketCap), d1Integer(candidate.liquidity), d1Integer(candidate.holders), d1Integer(candidate.volume24h), d1Text(candidate.price, "0"), `土狗雷达 · ${candidate.source}`, d1Text(ai.summary).slice(0, 1_200), candidate.firstSeenAt, id, d1Integer(evaluated.score.total)).run();
  }
  return { id, status, narrativeStatus: ai.status, tradeStatus: trade.status, decision: evaluated.decision, score: evaluated.score.total, hardFilterPassed: evaluated.hard.passed };
}
