"use client";
import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowLeft, ExternalLink, RefreshCw, Search } from "lucide-react";
import { EXCHANGE_LABELS, type Exchange } from "@/lib/exchange-intelligence";

export type ExchangePayload = { events: Record<string, any>[]; health: Record<string, any>[]; fetchedAt: string };
const typeLabels: Record<string, string> = { first_spot_listing: "首次现货上币", spot_pair_add: "新增现货交易对", contract_open: "合约开通", alpha_add: "币安 Alpha 纳入", alpha_remove: "币安 Alpha 移除", launch_activity: "Launchpad／Launchpool／打新", token_delisting: "下架币种", pair_delisting: "下架指定交易对" };
const fmt = (value: unknown) => value ? new Intl.DateTimeFormat("zh-CN", { timeZone: "Asia/Shanghai", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(String(value))) : "—";

export default function ExchangeDashboard({ initial }: { initial: ExchangePayload }) {
  const [data, setData] = useState(initial); const [exchange, setExchange] = useState("all"); const [type, setType] = useState("all"); const [market, setMarket] = useState("all"); const [status, setStatus] = useState("all"); const [q, setQ] = useState(""); const [error, setError] = useState(false);
  useEffect(() => { let active = true; const run = async () => { try { const params = new URLSearchParams(); if (exchange !== "all") params.set("exchange", exchange); if (type !== "all") params.set("type", type); if (market !== "all") params.set("market", market); if (status !== "all") params.set("status", status); if (q.trim()) params.set("q", q.trim()); const response = await fetch(`/api/exchange-events?${params}`, { cache: "no-store" }); if (!response.ok) throw new Error(); const next = await response.json() as ExchangePayload; if (active) { setData(next); setError(false); } } catch { if (active) setError(true); } }; void run(); const timer = setInterval(run, 15000); return () => { active = false; clearInterval(timer); }; }, [exchange, type, market, status, q]);
  const exchangeHealth = useMemo(() => { const grouped = new Map<string, Record<string, any>[]>(); for (const row of data.health) { const key = String(row.exchange); grouped.set(key, [...(grouped.get(key) || []), row]); } return [...grouped.entries()].map(([key, rows]) => ({ key, ok: rows.filter((row) => row.status === "healthy").length, total: rows.length })); }, [data.health]);
  return <main className="min-h-screen overflow-x-hidden bg-[#070a0f] text-slate-100">
    <header className="sticky top-0 z-30 border-b border-white/10 bg-[#070a0f]/90 backdrop-blur-xl"><div className="mx-auto flex min-h-16 max-w-[1500px] flex-wrap items-center justify-between gap-2 px-4 py-2 sm:px-7"><a href="/" className="inline-flex items-center gap-2 text-sm text-slate-300"><ArrowLeft size={16}/>KOL Signal</a><nav className="flex flex-wrap gap-2 text-xs"><a href="/radar" className="rounded-lg border border-white/10 px-3 py-2 text-slate-400">土狗雷达</a><span className="rounded-lg border border-cyan-300/20 bg-cyan-300/10 px-3 py-2 text-cyan-200">交易所动态</span><a href="/flows" className="rounded-lg border border-white/10 px-3 py-2 text-slate-400">大额资金流向</a></nav></div></header>
    <div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-7">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-2xl font-semibold">交易所动态</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">初始监控名单为十家交易所，并非永久不变的实时排名。公告与公开交易对接口分别采集，公告更新只修订原事件。</p></div><div className={`inline-flex items-center gap-2 text-xs ${error ? "text-amber-300" : "text-slate-500"}`}><RefreshCw size={13}/>{error ? "刷新失败，保留最近结果" : `自动刷新 · ${fmt(data.fetchedAt)}`}</div></div>
      <section className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-5 lg:grid-cols-10">{(Object.keys(EXCHANGE_LABELS) as Exchange[]).map((key) => { const h = exchangeHealth.find((x) => x.key === key); return <button type="button" onClick={() => setExchange(exchange === key ? "all" : key)} key={key} className={`rounded-xl border px-3 py-3 text-left ${exchange === key ? "border-cyan-300/30 bg-cyan-300/10" : "border-white/8 bg-white/[0.025]"}`}><div className="text-sm">{EXCHANGE_LABELS[key]}</div><div className={`mt-1 text-[11px] ${h?.ok === h?.total && h?.total ? "text-emerald-300" : h ? "text-amber-300" : "text-slate-600"}`}>{h ? `${h.ok}/${h.total} 数据源正常` : "待首次采集"}</div></button>; })}</section>
      <section className="mt-5 rounded-2xl border border-white/8 bg-[#0b1018]">
        <div className="grid gap-3 border-b border-white/8 p-4 sm:grid-cols-2 lg:grid-cols-5"><label className="relative lg:col-span-2"><Search size={15} className="absolute left-3 top-3 text-slate-600"/><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="搜索币种、交易对或公告" className="h-10 w-full rounded-xl border border-white/10 bg-black/20 pl-9 pr-3 text-sm outline-none"/></label><Select value={type} onChange={setType} options={{ all: "全部事件", ...typeLabels }}/><Select value={market} onChange={setMarket} options={{ all: "全部市场", spot: "现货", contract: "合约", alpha: "Alpha", activity: "活动" }}/><Select value={status} onChange={setStatus} options={{ all: "全部状态", announced: "已公告", effective: "已生效", cancelled: "已取消" }}/></div>
        <div className="divide-y divide-white/6">{data.events.map((event) => <article key={event.id} className="grid min-w-0 gap-3 p-4 lg:grid-cols-[180px_minmax(0,1fr)_190px]"><div className="flex flex-wrap items-start gap-2"><span className="rounded-md border border-cyan-300/20 bg-cyan-300/8 px-2 py-1 text-xs text-cyan-200">{EXCHANGE_LABELS[event.exchange as Exchange] || event.exchange}</span><span className="rounded-md border border-white/10 px-2 py-1 text-xs text-slate-400">{typeLabels[event.event_type] || event.event_type}</span></div><div className="min-w-0"><a href={event.source_url} target="_blank" rel="noreferrer" className="inline-flex max-w-full items-start gap-1.5 font-medium leading-6 hover:text-cyan-200"><span className="break-words [overflow-wrap:anywhere]">{event.title}</span><ExternalLink size={13} className="mt-1 shrink-0"/></a><div className="mt-2 flex flex-wrap gap-2 text-xs text-slate-500">{(event.pairs || []).map((pair: string) => <span key={pair} className="rounded bg-white/5 px-2 py-1">{pair}</span>)}<span>{event.market_type}</span><span>{event.status}</span><span>修订 {event.revision}</span></div></div><div className="grid grid-cols-2 gap-2 text-xs text-slate-500 lg:grid-cols-1"><Time label="公告" value={event.announcement_at}/><Time label="发现" value={event.discovered_at}/><Time label="预计生效" value={event.expected_effective_at}/><Time label="实际生效" value={event.actual_effective_at}/></div></article>)}{!data.events.length && <div className="grid min-h-56 place-items-center p-8 text-center"><div><Activity className="mx-auto mb-3 text-slate-700"/><p className="text-slate-300">尚无符合条件的真实事件</p><p className="mt-1 text-sm text-slate-600">等待官方公告或基线建立后的交易对变化，不使用静态样例。</p></div></div>}</div>
      </section>
    </div>
  </main>;
}
function Select({ value, onChange, options }: { value: string; onChange: (v: string) => void; options: Record<string, string> }) { return <select value={value} onChange={(e) => onChange(e.target.value)} className="h-10 min-w-0 rounded-xl border border-white/10 bg-[#0b1018] px-3 text-sm">{Object.entries(options).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select>; }
function Time({ label, value }: { label: string; value: unknown }) { return <div className="flex justify-between gap-2"><span>{label}</span><span className="text-slate-300">{fmt(value)}</span></div>; }
