"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Activity, ArrowLeft, ExternalLink, RefreshCw, Search } from "lucide-react";
import { EXCHANGE_LABELS, type Exchange } from "@/lib/exchange-intelligence";

export type ExchangeEvent = { id: number; exchange: Exchange; event_type: string; market_type: string; title: string; title_zh?: string | null; translation_status?: string; translation_provider?: string | null; pairs?: string[]; source_url: string; source_kind?: string; status: string; revision: number; announcement_at?: string | null; discovered_at?: string | null; expected_effective_at?: string | null; actual_effective_at?: string | null };
export type ExchangeHealth = { exchange: Exchange; source: string; status: string; last_error?: string | null };
export type ExchangePayload = { events: ExchangeEvent[]; health: ExchangeHealth[]; fetchedAt: string };
const typeLabels: Record<string, string> = { first_spot_listing: "首次现货上币", spot_pair_add: "新增现货交易对", contract_open: "合约开通", alpha_add: "币安 Alpha 纳入", alpha_remove: "币安 Alpha 移除", launch_activity: "Launchpad／Launchpool／打新", token_delisting: "下架币种", pair_delisting: "下架指定交易对" };
const marketLabels: Record<string,string> = { spot: "现货", contract: "合约", alpha: "Alpha", activity: "活动", unknown: "市场待核实" };
const statusLabels: Record<string,string> = { announced: "已公告", effective: "已生效", cancelled: "已取消" };
const fmt = (value: unknown) => value ? new Intl.DateTimeFormat("zh-CN", { timeZone: "Asia/Shanghai", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(String(value))) : "—";
function healthMessage(row: ExchangeHealth) { const raw=String(row.last_error||row.status); if(raw.includes("COINBASE_X_BEARER_TOKEN"))return "官方提前公告源未配置；公开交易对快照仍正常运行";if(raw.includes("UPBIT_ACCESS_KEY")||raw.includes("私有公告 WebSocket"))return "官方提前公告源未配置或连接已超时；公开交易对快照仍正常运行";if(raw==="healthy")return "正常";if(raw==="error")return "采集异常";return raw; }

export default function ExchangeDashboard({ initial }: { initial: ExchangePayload }) {
  const [data, setData] = useState(initial); const [exchange, setExchange] = useState("all"); const [type, setType] = useState("all"); const [market, setMarket] = useState("all"); const [status, setStatus] = useState("all"); const [q, setQ] = useState(""); const [error, setError] = useState(false);
  useEffect(() => { let active = true; const run = async () => { try { const params = new URLSearchParams(); if (exchange !== "all") params.set("exchange", exchange); if (type !== "all") params.set("type", type); if (market !== "all") params.set("market", market); if (status !== "all") params.set("status", status); if (q.trim()) params.set("q", q.trim()); const response = await fetch(`/api/exchange-events?${params}`, { cache: "no-store" }); if (!response.ok) throw new Error(); const next = await response.json() as ExchangePayload; if (active) { setData(next); setError(false); } } catch { if (active) setError(true); } }; void run(); const timer = setInterval(run, 15000); return () => { active = false; clearInterval(timer); }; }, [exchange, type, market, status, q]);
  const exchangeHealth = useMemo(() => { const grouped = new Map<string, ExchangeHealth[]>(); for (const row of data.health) { const key = String(row.exchange); grouped.set(key, [...(grouped.get(key) || []), row]); } return [...grouped.entries()].map(([key, rows]) => ({ key, ok: rows.filter((row) => row.status === "healthy").length, total: rows.length })); }, [data.health]);
  const announcementHealth = useMemo(() => data.health.filter((row) => String(row.source).endsWith("_official_announcements")), [data.health]);
  const thirdPartyHealth = useMemo(() => data.health.filter((row) => String(row.source).endsWith("_third_party_new_listings_feed")), [data.health]);
  const connectedAnnouncements = announcementHealth.filter((row) => row.status === "healthy").map((row) => EXCHANGE_LABELS[row.exchange as Exchange] || row.exchange);
  const blockedAnnouncements = announcementHealth.filter((row) => row.status !== "healthy");
  return <main className="min-h-screen overflow-x-hidden bg-[#070a0f] text-slate-100">
    <header className="sticky top-0 z-30 border-b border-white/10 bg-[#070a0f]/90 backdrop-blur-xl"><div className="mx-auto flex min-h-16 max-w-[1500px] flex-wrap items-center justify-between gap-2 px-4 py-2 sm:px-7"><Link href="/" className="inline-flex items-center gap-2 text-sm text-slate-300"><ArrowLeft size={16}/>KOL Signal</Link><nav className="flex flex-wrap gap-2 text-xs"><Link href="/radar" className="rounded-lg border border-white/10 px-3 py-2 text-slate-400">土狗雷达</Link><span className="rounded-lg border border-cyan-300/20 bg-cyan-300/10 px-3 py-2 text-cyan-200">交易所动态</span><Link href="/flows" className="rounded-lg border border-white/10 px-3 py-2 text-slate-400">大额资金流向</Link></nav></div></header>
    <div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-7">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-2xl font-semibold">交易所动态</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">初始监控名单为十家交易所，并非永久不变的实时排名。公告与公开交易对接口分别采集，公告更新只修订原事件。</p></div><div className={`inline-flex items-center gap-2 text-xs ${error ? "text-amber-300" : "text-slate-500"}`}><RefreshCw size={13}/>{error ? "刷新失败，保留最近结果" : `自动刷新 · ${fmt(data.fetchedAt)}`}</div></div>
      <section className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-5 lg:grid-cols-10">{(Object.keys(EXCHANGE_LABELS) as Exchange[]).map((key) => { const h = exchangeHealth.find((x) => x.key === key); return <button type="button" onClick={() => setExchange(exchange === key ? "all" : key)} key={key} className={`rounded-xl border px-3 py-3 text-left ${exchange === key ? "border-cyan-300/30 bg-cyan-300/10" : "border-white/8 bg-white/[0.025]"}`}><div className="text-sm">{EXCHANGE_LABELS[key]}</div><div className={`mt-1 text-[11px] ${h?.ok === h?.total && h?.total ? "text-emerald-300" : h ? "text-amber-300" : "text-slate-600"}`}>{h ? `${h.ok}/${h.total} 数据源正常` : "待首次采集"}</div></button>; })}</section>
      <section className="mt-3 rounded-2xl border border-white/8 bg-[#0b1018] p-4 text-xs leading-6 text-slate-400"><div><span className="text-emerald-300">真实官方公告已接通：</span>{connectedAnnouncements.length ? connectedAnnouncements.join("、") : "无"}</div>{blockedAnnouncements.length > 0 && <div className="mt-1"><span className="text-amber-300">官方提前公告覆盖不足：</span>{blockedAnnouncements.map((row) => `${EXCHANGE_LABELS[row.exchange as Exchange] || row.exchange}（${healthMessage(row)}）`).join("；")}</div>}<div className="mt-1"><span className="text-cyan-200">第三方发现：</span>{thirdPartyHealth.some((row) => row.status === "healthy") ? "New Listings Feed 已实测连接；事件会逐条标注第三方来源，并由官方交易对快照核验实际开通。" : "New Listings Feed 仅完成文档格式适配与契约测试，默认关闭，尚无真实流数据。"}</div><div className="mt-1 text-slate-600">Coinbase 与 Upbit 保留官方公开交易对快照；首次快照只建基线，不生成新上市事件。缺少提前公告源不会删除这两家。页面时间均为北京时间。</div></section>
      <section className="mt-5 rounded-2xl border border-white/8 bg-[#0b1018]">
        <div className="grid gap-3 border-b border-white/8 p-4 sm:grid-cols-2 lg:grid-cols-5"><label className="relative lg:col-span-2"><Search size={15} className="absolute left-3 top-3 text-slate-600"/><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="搜索币种、交易对或公告" className="h-10 w-full rounded-xl border border-white/10 bg-black/20 pl-9 pr-3 text-sm outline-none"/></label><Select value={type} onChange={setType} options={{ all: "全部事件", ...typeLabels }}/><Select value={market} onChange={setMarket} options={{ all: "全部市场", spot: "现货", contract: "合约", alpha: "Alpha", activity: "活动" }}/><Select value={status} onChange={setStatus} options={{ all: "全部状态", announced: "已公告", effective: "已生效", cancelled: "已取消" }}/></div>
        <div className="divide-y divide-white/6">{data.events.map((event) => {const translated=Boolean(event.title_zh);const displayTitle=event.title_zh||event.title;return <article key={event.id} className="grid min-w-0 gap-3 p-4 lg:grid-cols-[180px_minmax(0,1fr)_210px]"><div className="flex flex-wrap items-start gap-2"><span className="rounded-md border border-cyan-300/20 bg-cyan-300/8 px-2 py-1 text-xs text-cyan-200">{EXCHANGE_LABELS[event.exchange as Exchange] || event.exchange}</span><span className="rounded-md border border-white/10 px-2 py-1 text-xs text-slate-400">{typeLabels[event.event_type] || "事件类型待核实"}</span>{event.source_kind === "third_party_discovery" && <span className="rounded-md border border-amber-300/20 bg-amber-300/8 px-2 py-1 text-xs text-amber-200">第三方发现 · New Listings Feed</span>}</div><div className="min-w-0"><h2 className="break-words font-medium leading-6 [overflow-wrap:anywhere]">{displayTitle}</h2><div className="mt-1 flex flex-wrap items-center gap-2 text-xs"><a href={event.source_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-cyan-300 hover:text-cyan-200">查看原文<ExternalLink size={12}/></a>{!translated&&<span className="rounded border border-amber-300/20 bg-amber-300/8 px-1.5 py-0.5 text-amber-200">暂未翻译</span>}{event.translation_provider==="google"&&<span className="text-slate-500">由 Google 自动翻译</span>}</div><div className="mt-2 flex flex-wrap gap-2 text-xs text-slate-500">{(event.pairs || []).map((pair: string) => <span key={pair} className="rounded bg-white/5 px-2 py-1">{pair}</span>)}<span>{marketLabels[event.market_type] || "市场待核实"}</span><span>{statusLabels[event.status] || "状态待核实"}</span><span>修订 {event.revision}</span></div></div><div className="grid grid-cols-2 gap-2 text-xs text-slate-500 lg:grid-cols-1"><Time label="公告时间" value={event.announcement_at}/><Time label="发现时间" value={event.discovered_at}/><Time label="预计生效时间" value={event.expected_effective_at}/><Time label="实际生效时间" value={event.actual_effective_at}/></div></article>})}{!data.events.length && <div className="grid min-h-56 place-items-center p-8 text-center"><div><Activity className="mx-auto mb-3 text-slate-700"/><p className="text-slate-300">尚无符合条件的真实事件</p><p className="mt-1 text-sm text-slate-600">等待官方公告或基线建立后的交易对变化，不使用静态样例。</p></div></div>}</div>
      </section>
    </div>
  </main>;
}
function Select({ value, onChange, options }: { value: string; onChange: (v: string) => void; options: Record<string, string> }) { return <select value={value} onChange={(e) => onChange(e.target.value)} className="h-10 min-w-0 rounded-xl border border-white/10 bg-[#0b1018] px-3 text-sm">{Object.entries(options).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select>; }
function Time({ label, value }: { label: string; value: unknown }) { return <div className="flex justify-between gap-2"><span>{label}</span><span className="text-slate-300">{fmt(value)}</span></div>; }
