import { env } from "cloudflare:workers";
import { isMonitorAuthorized } from "@/lib/monitor-auth";
import { ANNOUNCEMENT_SOURCES, EXCHANGES, EXCHANGE_LABELS, PAIR_SOURCES, classifyAnnouncement, eventPriority, extractAnnouncementLinks, extractBinanceAnnouncements, normalizePairs, splitPair, type Exchange, type ExchangeEventType } from "@/lib/exchange-intelligence";
import { sendWeComMarkdown } from "@/lib/wecom";
import { AlertDeliveryError } from "@/lib/alert-delivery";

export const dynamic = "force-dynamic";
const headers = { "User-Agent": "KOL-Signal-Monitor/1.0 (+official-market-verification)", Accept: "application/json,text/html;q=0.9,*/*;q=0.8" };
async function sha(value: string) { const bytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return [...new Uint8Array(bytes)].map((b) => b.toString(16).padStart(2, "0")).join(""); }
function tokens(title: string) { return [...new Set((title.match(/\b[A-Z0-9]{2,12}(?:[-\/]?(?:USDT|USDC|USD|KRW))?\b/g) || []).filter((x) => !["THE", "WILL", "SPOT", "LIST", "WITH", "NEW", "AND", "FOR"].includes(x)))].slice(0, 20); }
function pairTokens(title: string) { return tokens(title).filter((x) => /(?:USDT|USDC|USD|KRW)$/.test(x)).map((x) => x.replace("/", "-")); }

async function saveEvent(db: D1Database, event: { eventKey: string; exchange: Exchange; eventType: ExchangeEventType; marketType: string; title: string; pairs?: string[]; sourceName: string; sourceUrl: string; sourceKind: string; announcementId?: string; announcementAt?: string | null; expectedEffectiveAt?: string | null; actualEffectiveAt?: string | null; status: string }, alert: boolean, now: string) {
  const pairs = event.pairs || pairTokens(event.title); const assets = [...new Set([...pairs.map((p) => splitPair(p).base), ...tokens(event.title).filter((t) => !/(USDT|USDC|USD|KRW)$/.test(t))])].slice(0, 20);
  const body = JSON.stringify({ ...event, pairs, assets }); const contentHash = await sha(body); const existing = await db.prepare("SELECT id,content_hash,revision FROM exchange_events WHERE event_key=?").bind(event.eventKey).first<{ id: number; content_hash: string; revision: number }>();
  if (existing?.content_hash === contentHash) return { id: existing.id, changed: false };
  if (existing) {
    const revision = existing.revision + 1;
    await db.batch([
      db.prepare("UPDATE exchange_events SET event_type=?,market_type=?,title=?,assets_json=?,pairs_json=?,source_url=?,announcement_at=?,expected_effective_at=?,actual_effective_at=?,status=?,priority=?,content_hash=?,revision=?,updated_at=? WHERE id=?").bind(event.eventType,event.marketType,event.title,JSON.stringify(assets),JSON.stringify(pairs),event.sourceUrl,event.announcementAt||null,event.expectedEffectiveAt||null,event.actualEffectiveAt||null,event.status,eventPriority(event.eventType,pairs),contentHash,revision,now,existing.id),
      db.prepare("INSERT INTO exchange_event_revisions (event_id,revision,content_hash,payload_json,recorded_at) VALUES (?,?,?,?,?)").bind(existing.id,revision,contentHash,body,now),
    ]);
    return { id: existing.id, changed: true };
  }
  const inserted = await db.prepare("INSERT INTO exchange_events (event_key,exchange,event_type,market_type,title,assets_json,pairs_json,conditions,announcement_id,source_name,source_url,source_kind,announcement_at,discovered_at,expected_effective_at,actual_effective_at,activity_start_at,activity_end_at,status,priority,content_hash,revision,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,?) RETURNING id").bind(event.eventKey,event.exchange,event.eventType,event.marketType,event.title,JSON.stringify(assets),JSON.stringify(pairs),null,event.announcementId||null,event.sourceName,event.sourceUrl,event.sourceKind,event.announcementAt||null,now,event.expectedEffectiveAt||null,event.actualEffectiveAt||null,null,null,event.status,eventPriority(event.eventType,pairs),contentHash,now).first<{id:number}>();
  if (inserted && alert && eventPriority(event.eventType,pairs) === "high") await db.prepare("INSERT OR IGNORE INTO exchange_alert_deliveries (event_id,delivery_key,status,attempts,next_attempt_at,payload_hash) VALUES (?,?, 'pending',0,?,?)").bind(inserted.id,`exchange:${event.eventKey}`,now,contentHash).run();
  if (inserted) await db.prepare("INSERT INTO exchange_event_revisions (event_id,revision,content_hash,payload_json,recorded_at) VALUES (?,1,?,?,?)").bind(inserted.id,contentHash,body,now).run();
  return { id: inserted?.id || 0, changed: true };
}

async function recordHealth(db: D1Database, source: string, exchange: Exchange, status: string, started: number, error: string | null, coverage: string[], now: string) {
  const previous = await db.prepare("SELECT consecutive_failures FROM exchange_collector_state WHERE source=?").bind(source).first<{consecutive_failures:number}>(); const failures = status === "healthy" ? 0 : (previous?.consecutive_failures || 0) + 1; const nextRetry = status === "healthy" ? null : new Date(Date.now() + Math.min(300_000, 2 ** Math.min(failures, 8) * 1000)).toISOString();
  await db.prepare("INSERT INTO exchange_collector_state (source,exchange,status,cursor,last_attempt_at,last_success_at,last_event_at,last_latency_ms,consecutive_failures,next_retry_at,last_error,coverage_json) VALUES (?,?,?,NULL,?,?,?,?,?,?,?,?) ON CONFLICT(source) DO UPDATE SET status=excluded.status,last_attempt_at=excluded.last_attempt_at,last_success_at=CASE WHEN excluded.status='healthy' THEN excluded.last_success_at ELSE exchange_collector_state.last_success_at END,last_latency_ms=excluded.last_latency_ms,consecutive_failures=excluded.consecutive_failures,next_retry_at=excluded.next_retry_at,last_error=excluded.last_error,coverage_json=excluded.coverage_json").bind(source,exchange,status,now,status==="healthy"?now:null,null,Date.now()-started,failures,nextRetry,error,JSON.stringify(coverage)).run();
}

async function collectPairs(db: D1Database, exchange: Exchange, marketType: "spot"|"contract", url: string, now: string) {
  const source = `${exchange}_pairs_${marketType}`; const started = Date.now();
  try {
    const response = await fetch(url,{headers,signal:AbortSignal.timeout(15_000)}); if (!response.ok) throw new Error(`HTTP ${response.status}`); const pairs = normalizePairs(exchange,marketType,await response.json()); if (!pairs.length) throw new Error("empty_pair_snapshot"); const contentHash=await sha(JSON.stringify(pairs));
    const previous=await db.prepare("SELECT pairs_json,content_hash FROM exchange_pair_snapshots WHERE exchange=? AND market_type=?").bind(exchange,marketType).first<{pairs_json:string;content_hash:string}>(); let created=0;
    if (!previous) await db.prepare("INSERT INTO exchange_pair_snapshots (exchange,market_type,pairs_json,content_hash,initialized_at,captured_at,source_url) VALUES (?,?,?,?,?,?,?)").bind(exchange,marketType,JSON.stringify(pairs),contentHash,now,now,url).run();
    else if (previous.content_hash !== contentHash) {
      const before=new Set<string>(JSON.parse(previous.pairs_json)); const after=new Set(pairs); const added=pairs.filter((p)=>!before.has(p)).slice(0,100); const removed=[...before].filter((p)=>!after.has(p)).slice(0,100);
      for (const pair of added) { await saveEvent(db,{eventKey:`pair:${exchange}:${marketType}:${pair}:open:${now}`,exchange,eventType:marketType==="spot"?"spot_pair_add":"contract_open",marketType,title:`${EXCHANGE_LABELS[exchange]} 已实际开通 ${pair} ${marketType==="spot"?"现货交易对":"合约"}`,pairs:[pair],sourceName:source,sourceUrl:url,sourceKind:"official_public_api",actualEffectiveAt:now,status:"effective"},true,now); created++; }
      for (const pair of removed) { await saveEvent(db,{eventKey:`pair:${exchange}:${marketType}:${pair}:closed:${now}`,exchange,eventType:"pair_delisting",marketType,title:`${EXCHANGE_LABELS[exchange]} 已实际停止 ${pair} ${marketType==="spot"?"现货交易对":"合约"}`,pairs:[pair],sourceName:source,sourceUrl:url,sourceKind:"official_public_api",actualEffectiveAt:now,status:"effective"},true,now); created++; }
      await db.prepare("UPDATE exchange_pair_snapshots SET pairs_json=?,content_hash=?,captured_at=?,source_url=? WHERE exchange=? AND market_type=?").bind(JSON.stringify(pairs),contentHash,now,url,exchange,marketType).run();
    } else await db.prepare("UPDATE exchange_pair_snapshots SET captured_at=? WHERE exchange=? AND market_type=?").bind(now,exchange,marketType).run();
    await recordHealth(db,source,exchange,"healthy",started,null,[marketType],now); return {source,count:pairs.length,created,baseline:!previous};
  } catch(error) { const message=error instanceof Error?error.message:String(error); await recordHealth(db,source,exchange,"error",started,message,[marketType],now); return {source,error:message}; }
}

async function collectAnnouncements(db:D1Database,exchange:Exchange,url:string,now:string) {
  const source=`${exchange}_official_announcements`; const started=Date.now(); const hadBaseline=!!(await db.prepare("SELECT last_success_at FROM exchange_collector_state WHERE source=? AND last_success_at IS NOT NULL").bind(source).first());
  try { const response=await fetch(url,{headers,signal:AbortSignal.timeout(15_000)}); if(!response.ok) throw new Error(`HTTP ${response.status}`); const raw=await response.text(); const links=exchange==="binance"?extractBinanceAnnouncements(JSON.parse(raw)):extractAnnouncementLinks(raw,url); if(!links.length) throw new Error("official_page_unparseable_or_empty"); let changed=0; for(const link of links.slice(0,30)){const kind=classifyAnnouncement(link.title); if(!kind)continue; const announcedAt="announcedAt" in link&&typeof link.announcedAt==="string"?link.announcedAt:null; const result=await saveEvent(db,{eventKey:`announcement:${exchange}:${link.id}`,exchange,eventType:kind.eventType,marketType:kind.marketType,title:link.title,announcementId:link.id,sourceName:source,sourceUrl:link.url,sourceKind:"official_announcement",announcementAt:announcedAt,status:"announced"},hadBaseline,now); if(result.changed)changed++;} await recordHealth(db,source,exchange,"healthy",started,null,["official_announcements"],now); return {source,count:links.length,changed,baseline:!hadBaseline}; }
  catch(error){const message=error instanceof Error?error.message:String(error); await recordHealth(db,source,exchange,"error",started,message,["official_announcements"],now); return {source,error:message};}
}

async function deliver(db:D1Database,now:string){const rows=await db.prepare("SELECT d.event_id,d.delivery_key,d.attempts,e.exchange,e.title,e.event_type,e.source_url FROM exchange_alert_deliveries d JOIN exchange_events e ON e.id=d.event_id WHERE d.status IN ('pending','retry') AND (d.next_attempt_at IS NULL OR d.next_attempt_at<=?) ORDER BY e.discovered_at LIMIT 5").bind(now).all<Record<string,unknown>>(); let sent=0; for(const row of rows.results){try{await sendWeComMarkdown(`## 交易所高优先动态\n> **${EXCHANGE_LABELS[String(row.exchange) as Exchange]} · ${String(row.title)}**\n> 类型：${String(row.event_type)}\n[查看官方原文](${String(row.source_url)})`); await db.prepare("UPDATE exchange_alert_deliveries SET status='sent',attempts=attempts+1,last_attempt_at=?,sent_at=?,last_error=NULL WHERE event_id=?").bind(now,now,row.event_id).run();sent++;}catch(error){const retryable=error instanceof AlertDeliveryError&&error.retryable; const attempts=Number(row.attempts)+1; await db.prepare("UPDATE exchange_alert_deliveries SET status=?,attempts=?,last_attempt_at=?,next_attempt_at=?,last_error=? WHERE event_id=?").bind(retryable&&attempts<5?"retry":"manual_review",attempts,now,retryable?new Date(Date.now()+Math.min(300000,2**attempts*15000)).toISOString():null,error instanceof Error?error.message:String(error),row.event_id).run();}} return {queued:rows.results.length,sent};}

export async function POST(request:Request){const source=env as unknown as Record<string,unknown>; if(!isMonitorAuthorized(request,typeof source.MONITOR_SECRET==="string"?source.MONITOR_SECRET:""))return Response.json({error:"unauthorized"},{status:401}); if(!env.DB)return Response.json({error:"database_unavailable"},{status:503}); const now=new Date().toISOString(); const results=[]; for(const exchange of EXCHANGES){results.push(await collectAnnouncements(env.DB,exchange,ANNOUNCEMENT_SOURCES[exchange],now)); const pairSources=PAIR_SOURCES[exchange]; results.push(await collectPairs(env.DB,exchange,"spot",pairSources.spot,now)); if(pairSources.contract)results.push(await collectPairs(env.DB,exchange,"contract",pairSources.contract,now));} return Response.json({ok:true,at:now,results,delivery:await deliver(env.DB,now)});}
